BEGIN;

ALTER TABLE coverage_reports
    ADD COLUMN IF NOT EXISTS cve_critical INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS cve_high INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS cve_medium INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS cve_low INTEGER NOT NULL DEFAULT 0;

ALTER TABLE coverage_report_packages
    ADD COLUMN IF NOT EXISTS cve_critical INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS cve_high INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS cve_medium INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS cve_low INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS cve_range_low REAL,
    ADD COLUMN IF NOT EXISTS cve_range_high REAL;

COMMIT;
