/* tslint:disable */
/* eslint-disable */
/**
 * ContentSourcesBackend
 * The API for the repositories of the content sources that you can use to create and manage repositories between third-party applications and the [Red Hat Hybrid Cloud Console](https://console.redhat.com). With these repositories, you can build and deploy images using Image Builder for Cloud, on-Premise, and Edge. You can handle tasks, search for required RPMs, fetch a GPGKey from the URL, and list the features within applications. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiBulkRemoveRpmsRequest
 */
export interface ApiBulkRemoveRpmsRequest {
    /**
     * Rpms to delete from upload repository
     * @type {Array<string>}
     * @memberof ApiBulkRemoveRpmsRequest
     */
    rpmUuids?: Array<string>;
}

/**
 * Check if a given object implements the ApiBulkRemoveRpmsRequest interface.
 */
export function instanceOfApiBulkRemoveRpmsRequest(value: object): value is ApiBulkRemoveRpmsRequest {
    return true;
}

export function ApiBulkRemoveRpmsRequestFromJSON(json: any): ApiBulkRemoveRpmsRequest {
    return ApiBulkRemoveRpmsRequestFromJSONTyped(json, false);
}

export function ApiBulkRemoveRpmsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiBulkRemoveRpmsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'rpmUuids': json['rpm_uuids'] == null ? undefined : json['rpm_uuids'],
    };
}

export function ApiBulkRemoveRpmsRequestToJSON(json: any): ApiBulkRemoveRpmsRequest {
    return ApiBulkRemoveRpmsRequestToJSONTyped(json, false);
}

export function ApiBulkRemoveRpmsRequestToJSONTyped(value?: ApiBulkRemoveRpmsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rpm_uuids': value['rpmUuids'],
    };
}

