/* tslint:disable */
/* eslint-disable */
/**
 * ContentSourcesBackend
 * The API for the repositories of the content sources that you can use to create and manage repositories between third-party applications and the [Red Hat Hybrid Cloud Console](https://console.redhat.com). With these repositories, you can build and deploy images using Image Builder for Cloud, on-Premise, and Edge. You can handle tasks, search for required RPMs, fetch a GPGKey from the URL, and list the features within applications. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiContentUnitSearchRequest
 */
export interface ApiContentUnitSearchRequest {
    /**
     * List of names to search using an exact match
     * @type {Array<string>}
     * @memberof ApiContentUnitSearchRequest
     */
    exactNames?: Array<string>;
    /**
     * Maximum number of records to return for the search
     * @type {number}
     * @memberof ApiContentUnitSearchRequest
     */
    limit?: number;
    /**
     * Search string to search content unit names
     * @type {string}
     * @memberof ApiContentUnitSearchRequest
     */
    search?: string;
    /**
     * URLs of repositories to search
     * @type {Array<string>}
     * @memberof ApiContentUnitSearchRequest
     */
    urls?: Array<string>;
    /**
     * List of repository UUIDs to search
     * @type {Array<string>}
     * @memberof ApiContentUnitSearchRequest
     */
    uuids?: Array<string>;
}

/**
 * Check if a given object implements the ApiContentUnitSearchRequest interface.
 */
export function instanceOfApiContentUnitSearchRequest(value: object): value is ApiContentUnitSearchRequest {
    return true;
}

export function ApiContentUnitSearchRequestFromJSON(json: any): ApiContentUnitSearchRequest {
    return ApiContentUnitSearchRequestFromJSONTyped(json, false);
}

export function ApiContentUnitSearchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiContentUnitSearchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'exactNames': json['exact_names'] == null ? undefined : json['exact_names'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'search': json['search'] == null ? undefined : json['search'],
        'urls': json['urls'] == null ? undefined : json['urls'],
        'uuids': json['uuids'] == null ? undefined : json['uuids'],
    };
}

export function ApiContentUnitSearchRequestToJSON(json: any): ApiContentUnitSearchRequest {
    return ApiContentUnitSearchRequestToJSONTyped(json, false);
}

export function ApiContentUnitSearchRequestToJSONTyped(value?: ApiContentUnitSearchRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'exact_names': value['exactNames'],
        'limit': value['limit'],
        'search': value['search'],
        'urls': value['urls'],
        'uuids': value['uuids'],
    };
}

