/* tslint:disable */
/* eslint-disable */
/**
 * ContentSourcesBackend
 * The API for the repositories of the content sources that you can use to create and manage repositories between third-party applications and the [Red Hat Hybrid Cloud Console](https://console.redhat.com). With these repositories, you can build and deploy images using Image Builder for Cloud, on-Premise, and Edge. You can handle tasks, search for required RPMs, fetch a GPGKey from the URL, and list the features within applications. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiCoverageReportPackageItem } from './ApiCoverageReportPackageItem';
import {
    ApiCoverageReportPackageItemFromJSON,
    ApiCoverageReportPackageItemFromJSONTyped,
    ApiCoverageReportPackageItemToJSON,
    ApiCoverageReportPackageItemToJSONTyped,
} from './ApiCoverageReportPackageItem';

/**
 * 
 * @export
 * @interface ApiCoverageReportPackagesResponse
 */
export interface ApiCoverageReportPackagesResponse {
    /**
     * 
     * @type {number}
     * @memberof ApiCoverageReportPackagesResponse
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiCoverageReportPackagesResponse
     */
    offset?: number;
    /**
     * 
     * @type {Array<ApiCoverageReportPackageItem>}
     * @memberof ApiCoverageReportPackagesResponse
     */
    results?: Array<ApiCoverageReportPackageItem>;
    /**
     * 
     * @type {number}
     * @memberof ApiCoverageReportPackagesResponse
     */
    total?: number;
}

/**
 * Check if a given object implements the ApiCoverageReportPackagesResponse interface.
 */
export function instanceOfApiCoverageReportPackagesResponse(value: object): value is ApiCoverageReportPackagesResponse {
    return true;
}

export function ApiCoverageReportPackagesResponseFromJSON(json: any): ApiCoverageReportPackagesResponse {
    return ApiCoverageReportPackagesResponseFromJSONTyped(json, false);
}

export function ApiCoverageReportPackagesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiCoverageReportPackagesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'limit': json['limit'] == null ? undefined : json['limit'],
        'offset': json['offset'] == null ? undefined : json['offset'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(ApiCoverageReportPackageItemFromJSON)),
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function ApiCoverageReportPackagesResponseToJSON(json: any): ApiCoverageReportPackagesResponse {
    return ApiCoverageReportPackagesResponseToJSONTyped(json, false);
}

export function ApiCoverageReportPackagesResponseToJSONTyped(value?: ApiCoverageReportPackagesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'limit': value['limit'],
        'offset': value['offset'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(ApiCoverageReportPackageItemToJSON)),
        'total': value['total'],
    };
}

