/* tslint:disable */
/* eslint-disable */
/**
 * ContentSourcesBackend
 * The API for the repositories of the content sources that you can use to create and manage repositories between third-party applications and the [Red Hat Hybrid Cloud Console](https://console.redhat.com). With these repositories, you can build and deploy images using Image Builder for Cloud, on-Premise, and Edge. You can handle tasks, search for required RPMs, fetch a GPGKey from the URL, and list the features within applications. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiEcosystemCoverageSummary } from './ApiEcosystemCoverageSummary';
import {
    ApiEcosystemCoverageSummaryFromJSON,
    ApiEcosystemCoverageSummaryFromJSONTyped,
    ApiEcosystemCoverageSummaryToJSON,
    ApiEcosystemCoverageSummaryToJSONTyped,
} from './ApiEcosystemCoverageSummary';

/**
 * 
 * @export
 * @interface ApiCoverageReportResponse
 */
export interface ApiCoverageReportResponse {
    /**
     * Error if coverage analysis task failed
     * @type {string}
     * @memberof ApiCoverageReportResponse
     */
    analysisTaskError?: string;
    /**
     * UUID of the coverage analysis task
     * @type {string}
     * @memberof ApiCoverageReportResponse
     */
    analysisTaskUuid?: string;
    /**
     * Timestamp when coverage analysis finished
     * @type {string}
     * @memberof ApiCoverageReportResponse
     */
    completedAt?: string;
    /**
     * Timestamp when the report was created
     * @type {string}
     * @memberof ApiCoverageReportResponse
     */
    createdAt?: string;
    /**
     * Per-ecosystem breakdown
     * @type {Array<ApiEcosystemCoverageSummary>}
     * @memberof ApiCoverageReportResponse
     */
    ecosystemCoverageSummary?: Array<ApiEcosystemCoverageSummary>;
    /**
     * Number of packages with name and version found
     * @type {number}
     * @memberof ApiCoverageReportResponse
     */
    exactMatches?: number;
    /**
     * Detected manifest format
     * @type {string}
     * @memberof ApiCoverageReportResponse
     */
    inputFormat?: string;
    /**
     * Number of packages with name found but not version
     * @type {number}
     * @memberof ApiCoverageReportResponse
     */
    partialMatches?: number;
    /**
     * Coverage analysis task status
     * @type {string}
     * @memberof ApiCoverageReportResponse
     */
    status?: string;
    /**
     * Total packages parsed from the manifest
     * @type {number}
     * @memberof ApiCoverageReportResponse
     */
    total?: number;
    /**
     * Number of packages with name not found
     * @type {number}
     * @memberof ApiCoverageReportResponse
     */
    unmatched?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiCoverageReportResponse
     */
    uuid?: string;
}

/**
 * Check if a given object implements the ApiCoverageReportResponse interface.
 */
export function instanceOfApiCoverageReportResponse(value: object): value is ApiCoverageReportResponse {
    return true;
}

export function ApiCoverageReportResponseFromJSON(json: any): ApiCoverageReportResponse {
    return ApiCoverageReportResponseFromJSONTyped(json, false);
}

export function ApiCoverageReportResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiCoverageReportResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'analysisTaskError': json['analysis_task_error'] == null ? undefined : json['analysis_task_error'],
        'analysisTaskUuid': json['analysis_task_uuid'] == null ? undefined : json['analysis_task_uuid'],
        'completedAt': json['completed_at'] == null ? undefined : json['completed_at'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'ecosystemCoverageSummary': json['ecosystem_coverage_summary'] == null ? undefined : ((json['ecosystem_coverage_summary'] as Array<any>).map(ApiEcosystemCoverageSummaryFromJSON)),
        'exactMatches': json['exact_matches'] == null ? undefined : json['exact_matches'],
        'inputFormat': json['input_format'] == null ? undefined : json['input_format'],
        'partialMatches': json['partial_matches'] == null ? undefined : json['partial_matches'],
        'status': json['status'] == null ? undefined : json['status'],
        'total': json['total'] == null ? undefined : json['total'],
        'unmatched': json['unmatched'] == null ? undefined : json['unmatched'],
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
    };
}

export function ApiCoverageReportResponseToJSON(json: any): ApiCoverageReportResponse {
    return ApiCoverageReportResponseToJSONTyped(json, false);
}

export function ApiCoverageReportResponseToJSONTyped(value?: ApiCoverageReportResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'analysis_task_error': value['analysisTaskError'],
        'analysis_task_uuid': value['analysisTaskUuid'],
        'completed_at': value['completedAt'],
        'created_at': value['createdAt'],
        'ecosystem_coverage_summary': value['ecosystemCoverageSummary'] == null ? undefined : ((value['ecosystemCoverageSummary'] as Array<any>).map(ApiEcosystemCoverageSummaryToJSON)),
        'exact_matches': value['exactMatches'],
        'input_format': value['inputFormat'],
        'partial_matches': value['partialMatches'],
        'status': value['status'],
        'total': value['total'],
        'unmatched': value['unmatched'],
        'uuid': value['uuid'],
    };
}

