/* tslint:disable */
/* eslint-disable */
/**
 * ContentSourcesBackend
 * The API for the repositories of the content sources that you can use to create and manage repositories between third-party applications and the [Red Hat Hybrid Cloud Console](https://console.redhat.com). With these repositories, you can build and deploy images using Image Builder for Cloud, on-Premise, and Edge. You can handle tasks, search for required RPMs, fetch a GPGKey from the URL, and list the features within applications. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiDetectRpmsResponse
 */
export interface ApiDetectRpmsResponse {
    /**
     * List of rpm names found in given repositories
     * @type {Array<string>}
     * @memberof ApiDetectRpmsResponse
     */
    found?: Array<string>;
    /**
     * List of rpm names not found in given repositories
     * @type {Array<string>}
     * @memberof ApiDetectRpmsResponse
     */
    missing?: Array<string>;
}

/**
 * Check if a given object implements the ApiDetectRpmsResponse interface.
 */
export function instanceOfApiDetectRpmsResponse(value: object): value is ApiDetectRpmsResponse {
    return true;
}

export function ApiDetectRpmsResponseFromJSON(json: any): ApiDetectRpmsResponse {
    return ApiDetectRpmsResponseFromJSONTyped(json, false);
}

export function ApiDetectRpmsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiDetectRpmsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'found': json['found'] == null ? undefined : json['found'],
        'missing': json['missing'] == null ? undefined : json['missing'],
    };
}

export function ApiDetectRpmsResponseToJSON(json: any): ApiDetectRpmsResponse {
    return ApiDetectRpmsResponseToJSONTyped(json, false);
}

export function ApiDetectRpmsResponseToJSONTyped(value?: ApiDetectRpmsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'found': value['found'],
        'missing': value['missing'],
    };
}

