/* tslint:disable */
/* eslint-disable */
/**
 * ContentSourcesBackend
 * The API for the repositories of the content sources that you can use to create and manage repositories between third-party applications and the [Red Hat Hybrid Cloud Console](https://console.redhat.com). With these repositories, you can build and deploy images using Image Builder for Cloud, on-Premise, and Edge. You can handle tasks, search for required RPMs, fetch a GPGKey from the URL, and list the features within applications. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiExtendedReleaseArchitecture } from './ApiExtendedReleaseArchitecture';
import {
    ApiExtendedReleaseArchitectureFromJSON,
    ApiExtendedReleaseArchitectureFromJSONTyped,
    ApiExtendedReleaseArchitectureToJSON,
    ApiExtendedReleaseArchitectureToJSONTyped,
} from './ApiExtendedReleaseArchitecture';

/**
 * 
 * @export
 * @interface ApiExtendedReleaseStream
 */
export interface ApiExtendedReleaseStream {
    /**
     * 
     * @type {Array<ApiExtendedReleaseArchitecture>}
     * @memberof ApiExtendedReleaseStream
     */
    architectures?: Array<ApiExtendedReleaseArchitecture>;
    /**
     * 
     * @type {string}
     * @memberof ApiExtendedReleaseStream
     */
    label?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiExtendedReleaseStream
     */
    name?: string;
}

/**
 * Check if a given object implements the ApiExtendedReleaseStream interface.
 */
export function instanceOfApiExtendedReleaseStream(value: object): value is ApiExtendedReleaseStream {
    return true;
}

export function ApiExtendedReleaseStreamFromJSON(json: any): ApiExtendedReleaseStream {
    return ApiExtendedReleaseStreamFromJSONTyped(json, false);
}

export function ApiExtendedReleaseStreamFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiExtendedReleaseStream {
    if (json == null) {
        return json;
    }
    return {
        
        'architectures': json['architectures'] == null ? undefined : ((json['architectures'] as Array<any>).map(ApiExtendedReleaseArchitectureFromJSON)),
        'label': json['label'] == null ? undefined : json['label'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function ApiExtendedReleaseStreamToJSON(json: any): ApiExtendedReleaseStream {
    return ApiExtendedReleaseStreamToJSONTyped(json, false);
}

export function ApiExtendedReleaseStreamToJSONTyped(value?: ApiExtendedReleaseStream | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'architectures': value['architectures'] == null ? undefined : ((value['architectures'] as Array<any>).map(ApiExtendedReleaseArchitectureToJSON)),
        'label': value['label'],
        'name': value['name'],
    };
}

