/* tslint:disable */
/* eslint-disable */
/**
 * ContentSourcesBackend
 * The API for the repositories of the content sources that you can use to create and manage repositories between third-party applications and the [Red Hat Hybrid Cloud Console](https://console.redhat.com). With these repositories, you can build and deploy images using Image Builder for Cloud, on-Premise, and Edge. You can handle tasks, search for required RPMs, fetch a GPGKey from the URL, and list the features within applications. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiLightwellPackageVersionResponse
 */
export interface ApiLightwellPackageVersionResponse {
    /**
     * 
     * @type {string}
     * @memberof ApiLightwellPackageVersionResponse
     */
    coordinates?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiLightwellPackageVersionResponse
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiLightwellPackageVersionResponse
     */
    ecosystem?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiLightwellPackageVersionResponse
     */
    group?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiLightwellPackageVersionResponse
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiLightwellPackageVersionResponse
     */
    purl?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiLightwellPackageVersionResponse
     */
    release?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiLightwellPackageVersionResponse
     */
    repository?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiLightwellPackageVersionResponse
     */
    repositoryUuid?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiLightwellPackageVersionResponse
     */
    version?: string;
}

/**
 * Check if a given object implements the ApiLightwellPackageVersionResponse interface.
 */
export function instanceOfApiLightwellPackageVersionResponse(value: object): value is ApiLightwellPackageVersionResponse {
    return true;
}

export function ApiLightwellPackageVersionResponseFromJSON(json: any): ApiLightwellPackageVersionResponse {
    return ApiLightwellPackageVersionResponseFromJSONTyped(json, false);
}

export function ApiLightwellPackageVersionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiLightwellPackageVersionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'coordinates': json['coordinates'] == null ? undefined : json['coordinates'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'ecosystem': json['ecosystem'] == null ? undefined : json['ecosystem'],
        'group': json['group'] == null ? undefined : json['group'],
        'name': json['name'] == null ? undefined : json['name'],
        'purl': json['purl'] == null ? undefined : json['purl'],
        'release': json['release'] == null ? undefined : json['release'],
        'repository': json['repository'] == null ? undefined : json['repository'],
        'repositoryUuid': json['repository_uuid'] == null ? undefined : json['repository_uuid'],
        'version': json['version'] == null ? undefined : json['version'],
    };
}

export function ApiLightwellPackageVersionResponseToJSON(json: any): ApiLightwellPackageVersionResponse {
    return ApiLightwellPackageVersionResponseToJSONTyped(json, false);
}

export function ApiLightwellPackageVersionResponseToJSONTyped(value?: ApiLightwellPackageVersionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'coordinates': value['coordinates'],
        'created_at': value['createdAt'],
        'ecosystem': value['ecosystem'],
        'group': value['group'],
        'name': value['name'],
        'purl': value['purl'],
        'release': value['release'],
        'repository': value['repository'],
        'repository_uuid': value['repositoryUuid'],
        'version': value['version'],
    };
}

