/* tslint:disable */
/* eslint-disable */
/**
 * ContentSourcesBackend
 * The API for the repositories of the content sources that you can use to create and manage repositories between third-party applications and the [Red Hat Hybrid Cloud Console](https://console.redhat.com). With these repositories, you can build and deploy images using Image Builder for Cloud, on-Premise, and Edge. You can handle tasks, search for required RPMs, fetch a GPGKey from the URL, and list the features within applications. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiSnapshotForDate } from './ApiSnapshotForDate';
import {
    ApiSnapshotForDateFromJSON,
    ApiSnapshotForDateFromJSONTyped,
    ApiSnapshotForDateToJSON,
    ApiSnapshotForDateToJSONTyped,
} from './ApiSnapshotForDate';

/**
 * 
 * @export
 * @interface ApiListSnapshotByDateResponse
 */
export interface ApiListSnapshotByDateResponse {
    /**
     * Requested Data
     * @type {Array<ApiSnapshotForDate>}
     * @memberof ApiListSnapshotByDateResponse
     */
    data?: Array<ApiSnapshotForDate>;
}

/**
 * Check if a given object implements the ApiListSnapshotByDateResponse interface.
 */
export function instanceOfApiListSnapshotByDateResponse(value: object): value is ApiListSnapshotByDateResponse {
    return true;
}

export function ApiListSnapshotByDateResponseFromJSON(json: any): ApiListSnapshotByDateResponse {
    return ApiListSnapshotByDateResponseFromJSONTyped(json, false);
}

export function ApiListSnapshotByDateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiListSnapshotByDateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ApiSnapshotForDateFromJSON)),
    };
}

export function ApiListSnapshotByDateResponseToJSON(json: any): ApiListSnapshotByDateResponse {
    return ApiListSnapshotByDateResponseToJSONTyped(json, false);
}

export function ApiListSnapshotByDateResponseToJSONTyped(value?: ApiListSnapshotByDateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ApiSnapshotForDateToJSON)),
    };
}

