/* tslint:disable */
/* eslint-disable */
/**
 * ContentSourcesBackend
 * The API for the repositories of the content sources that you can use to create and manage repositories between third-party applications and the [Red Hat Hybrid Cloud Console](https://console.redhat.com). With these repositories, you can build and deploy images using Image Builder for Cloud, on-Premise, and Edge. You can handle tasks, search for required RPMs, fetch a GPGKey from the URL, and list the features within applications. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiLightwellTokenCreateRequest
 */
export interface ApiLightwellTokenCreateRequest {
    /**
     * Optional expiry; defaults to 365 days from creation (max 365 days)
     * @type {string}
     * @memberof ApiLightwellTokenCreateRequest
     */
    expiresAt?: string;
    /**
     * Human-readable token name
     * @type {string}
     * @memberof ApiLightwellTokenCreateRequest
     */
    name?: string;
    /**
     * Associated user ID; defaults to the calling user
     * @type {string}
     * @memberof ApiLightwellTokenCreateRequest
     */
    userId?: string;
}

/**
 * Check if a given object implements the ApiLightwellTokenCreateRequest interface.
 */
export function instanceOfApiLightwellTokenCreateRequest(value: object): value is ApiLightwellTokenCreateRequest {
    return true;
}

export function ApiLightwellTokenCreateRequestFromJSON(json: any): ApiLightwellTokenCreateRequest {
    return ApiLightwellTokenCreateRequestFromJSONTyped(json, false);
}

export function ApiLightwellTokenCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiLightwellTokenCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'expiresAt': json['expires_at'] == null ? undefined : json['expires_at'],
        'name': json['name'] == null ? undefined : json['name'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
    };
}

export function ApiLightwellTokenCreateRequestToJSON(json: any): ApiLightwellTokenCreateRequest {
    return ApiLightwellTokenCreateRequestToJSONTyped(json, false);
}

export function ApiLightwellTokenCreateRequestToJSONTyped(value?: ApiLightwellTokenCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'expires_at': value['expiresAt'],
        'name': value['name'],
        'user_id': value['userId'],
    };
}

