/* tslint:disable */
/* eslint-disable */
/**
 * ContentSourcesBackend
 * The API for the repositories of the content sources that you can use to create and manage repositories between third-party applications and the [Red Hat Hybrid Cloud Console](https://console.redhat.com). With these repositories, you can build and deploy images using Image Builder for Cloud, on-Premise, and Edge. You can handle tasks, search for required RPMs, fetch a GPGKey from the URL, and list the features within applications. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiMavenPackageDetailResponse } from './ApiMavenPackageDetailResponse';
import {
    ApiMavenPackageDetailResponseFromJSON,
    ApiMavenPackageDetailResponseFromJSONTyped,
    ApiMavenPackageDetailResponseToJSON,
    ApiMavenPackageDetailResponseToJSONTyped,
} from './ApiMavenPackageDetailResponse';

/**
 * 
 * @export
 * @interface ApiMavenPackageVersionsResponse
 */
export interface ApiMavenPackageVersionsResponse {
    /**
     * 
     * @type {string}
     * @memberof ApiMavenPackageVersionsResponse
     */
    group?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiMavenPackageVersionsResponse
     */
    name?: string;
    /**
     * 
     * @type {Array<ApiMavenPackageDetailResponse>}
     * @memberof ApiMavenPackageVersionsResponse
     */
    versions?: Array<ApiMavenPackageDetailResponse>;
}

/**
 * Check if a given object implements the ApiMavenPackageVersionsResponse interface.
 */
export function instanceOfApiMavenPackageVersionsResponse(value: object): value is ApiMavenPackageVersionsResponse {
    return true;
}

export function ApiMavenPackageVersionsResponseFromJSON(json: any): ApiMavenPackageVersionsResponse {
    return ApiMavenPackageVersionsResponseFromJSONTyped(json, false);
}

export function ApiMavenPackageVersionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiMavenPackageVersionsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'group': json['group'] == null ? undefined : json['group'],
        'name': json['name'] == null ? undefined : json['name'],
        'versions': json['versions'] == null ? undefined : ((json['versions'] as Array<any>).map(ApiMavenPackageDetailResponseFromJSON)),
    };
}

export function ApiMavenPackageVersionsResponseToJSON(json: any): ApiMavenPackageVersionsResponse {
    return ApiMavenPackageVersionsResponseToJSONTyped(json, false);
}

export function ApiMavenPackageVersionsResponseToJSONTyped(value?: ApiMavenPackageVersionsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'group': value['group'],
        'name': value['name'],
        'versions': value['versions'] == null ? undefined : ((value['versions'] as Array<any>).map(ApiMavenPackageDetailResponseToJSON)),
    };
}

