/* tslint:disable */
/* eslint-disable */
/**
 * ContentSourcesBackend
 * The API for the repositories of the content sources that you can use to create and manage repositories between third-party applications and the [Red Hat Hybrid Cloud Console](https://console.redhat.com). With these repositories, you can build and deploy images using Image Builder for Cloud, on-Premise, and Edge. You can handle tasks, search for required RPMs, fetch a GPGKey from the URL, and list the features within applications. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiNpmTarball
 */
export interface ApiNpmTarball {
    /**
     * 
     * @type {string}
     * @memberof ApiNpmTarball
     */
    filename?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiNpmTarball
     */
    relativePath?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiNpmTarball
     */
    sha256?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiNpmTarball
     */
    size?: number;
}

/**
 * Check if a given object implements the ApiNpmTarball interface.
 */
export function instanceOfApiNpmTarball(value: object): value is ApiNpmTarball {
    return true;
}

export function ApiNpmTarballFromJSON(json: any): ApiNpmTarball {
    return ApiNpmTarballFromJSONTyped(json, false);
}

export function ApiNpmTarballFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiNpmTarball {
    if (json == null) {
        return json;
    }
    return {
        
        'filename': json['filename'] == null ? undefined : json['filename'],
        'relativePath': json['relative_path'] == null ? undefined : json['relative_path'],
        'sha256': json['sha256'] == null ? undefined : json['sha256'],
        'size': json['size'] == null ? undefined : json['size'],
    };
}

export function ApiNpmTarballToJSON(json: any): ApiNpmTarball {
    return ApiNpmTarballToJSONTyped(json, false);
}

export function ApiNpmTarballToJSONTyped(value?: ApiNpmTarball | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'filename': value['filename'],
        'relative_path': value['relativePath'],
        'sha256': value['sha256'],
        'size': value['size'],
    };
}

