/* tslint:disable */
/* eslint-disable */
/**
 * ContentSourcesBackend
 * The API for the repositories of the content sources that you can use to create and manage repositories between third-party applications and the [Red Hat Hybrid Cloud Console](https://console.redhat.com). With these repositories, you can build and deploy images using Image Builder for Cloud, on-Premise, and Edge. You can handle tasks, search for required RPMs, fetch a GPGKey from the URL, and list the features within applications. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiReleaseInfo } from './ApiReleaseInfo';
import {
    ApiReleaseInfoFromJSON,
    ApiReleaseInfoFromJSONTyped,
    ApiReleaseInfoToJSON,
    ApiReleaseInfoToJSONTyped,
} from './ApiReleaseInfo';

/**
 * 
 * @export
 * @interface ApiPackageItem
 */
export interface ApiPackageItem {
    /**
     * 
     * @type {string}
     * @memberof ApiPackageItem
     */
    group?: string;
    /**
     * 
     * @type {Array<ApiReleaseInfo>}
     * @memberof ApiPackageItem
     */
    latestReleases?: Array<ApiReleaseInfo>;
    /**
     * 
     * @type {string}
     * @memberof ApiPackageItem
     */
    name?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApiPackageItem
     */
    versions?: Array<string>;
}

/**
 * Check if a given object implements the ApiPackageItem interface.
 */
export function instanceOfApiPackageItem(value: object): value is ApiPackageItem {
    return true;
}

export function ApiPackageItemFromJSON(json: any): ApiPackageItem {
    return ApiPackageItemFromJSONTyped(json, false);
}

export function ApiPackageItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiPackageItem {
    if (json == null) {
        return json;
    }
    return {
        
        'group': json['group'] == null ? undefined : json['group'],
        'latestReleases': json['latest_releases'] == null ? undefined : ((json['latest_releases'] as Array<any>).map(ApiReleaseInfoFromJSON)),
        'name': json['name'] == null ? undefined : json['name'],
        'versions': json['versions'] == null ? undefined : json['versions'],
    };
}

export function ApiPackageItemToJSON(json: any): ApiPackageItem {
    return ApiPackageItemToJSONTyped(json, false);
}

export function ApiPackageItemToJSONTyped(value?: ApiPackageItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'group': value['group'],
        'latest_releases': value['latestReleases'] == null ? undefined : ((value['latestReleases'] as Array<any>).map(ApiReleaseInfoToJSON)),
        'name': value['name'],
        'versions': value['versions'],
    };
}

