/* tslint:disable */
/* eslint-disable */
/**
 * ContentSourcesBackend
 * The API for the repositories of the content sources that you can use to create and manage repositories between third-party applications and the [Red Hat Hybrid Cloud Console](https://console.redhat.com). With these repositories, you can build and deploy images using Image Builder for Cloud, on-Premise, and Edge. You can handle tasks, search for required RPMs, fetch a GPGKey from the URL, and list the features within applications. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiPythonPackageDetailResponse } from './ApiPythonPackageDetailResponse';
import {
    ApiPythonPackageDetailResponseFromJSON,
    ApiPythonPackageDetailResponseFromJSONTyped,
    ApiPythonPackageDetailResponseToJSON,
    ApiPythonPackageDetailResponseToJSONTyped,
} from './ApiPythonPackageDetailResponse';

/**
 * 
 * @export
 * @interface ApiPythonPackageVersionsResponse
 */
export interface ApiPythonPackageVersionsResponse {
    /**
     * 
     * @type {string}
     * @memberof ApiPythonPackageVersionsResponse
     */
    name?: string;
    /**
     * 
     * @type {Array<ApiPythonPackageDetailResponse>}
     * @memberof ApiPythonPackageVersionsResponse
     */
    versions?: Array<ApiPythonPackageDetailResponse>;
}

/**
 * Check if a given object implements the ApiPythonPackageVersionsResponse interface.
 */
export function instanceOfApiPythonPackageVersionsResponse(value: object): value is ApiPythonPackageVersionsResponse {
    return true;
}

export function ApiPythonPackageVersionsResponseFromJSON(json: any): ApiPythonPackageVersionsResponse {
    return ApiPythonPackageVersionsResponseFromJSONTyped(json, false);
}

export function ApiPythonPackageVersionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiPythonPackageVersionsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'versions': json['versions'] == null ? undefined : ((json['versions'] as Array<any>).map(ApiPythonPackageDetailResponseFromJSON)),
    };
}

export function ApiPythonPackageVersionsResponseToJSON(json: any): ApiPythonPackageVersionsResponse {
    return ApiPythonPackageVersionsResponseToJSONTyped(json, false);
}

export function ApiPythonPackageVersionsResponseToJSONTyped(value?: ApiPythonPackageVersionsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'versions': value['versions'] == null ? undefined : ((value['versions'] as Array<any>).map(ApiPythonPackageDetailResponseToJSON)),
    };
}

