/* tslint:disable */
/* eslint-disable */
/**
 * ContentSourcesBackend
 * The API for the repositories of the content sources that you can use to create and manage repositories between third-party applications and the [Red Hat Hybrid Cloud Console](https://console.redhat.com). With these repositories, you can build and deploy images using Image Builder for Cloud, on-Premise, and Edge. You can handle tasks, search for required RPMs, fetch a GPGKey from the URL, and list the features within applications. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiPackageDetailBuild
 */
export interface ApiPackageDetailBuild {
    /**
     * 
     * @type {string}
     * @memberof ApiPackageDetailBuild
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiPackageDetailBuild
     */
    release?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiPackageDetailBuild
     */
    version?: string;
}

/**
 * Check if a given object implements the ApiPackageDetailBuild interface.
 */
export function instanceOfApiPackageDetailBuild(value: object): value is ApiPackageDetailBuild {
    return true;
}

export function ApiPackageDetailBuildFromJSON(json: any): ApiPackageDetailBuild {
    return ApiPackageDetailBuildFromJSONTyped(json, false);
}

export function ApiPackageDetailBuildFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiPackageDetailBuild {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'release': json['release'] == null ? undefined : json['release'],
        'version': json['version'] == null ? undefined : json['version'],
    };
}

export function ApiPackageDetailBuildToJSON(json: any): ApiPackageDetailBuild {
    return ApiPackageDetailBuildToJSONTyped(json, false);
}

export function ApiPackageDetailBuildToJSONTyped(value?: ApiPackageDetailBuild | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'],
        'release': value['release'],
        'version': value['version'],
    };
}

