/* tslint:disable */
/* eslint-disable */
/**
 * ContentSourcesBackend
 * The API for the repositories of the content sources that you can use to create and manage repositories between third-party applications and the [Red Hat Hybrid Cloud Console](https://console.redhat.com). With these repositories, you can build and deploy images using Image Builder for Cloud, on-Premise, and Edge. You can handle tasks, search for required RPMs, fetch a GPGKey from the URL, and list the features within applications. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiReleaseInfo } from './ApiReleaseInfo';
import {
    ApiReleaseInfoFromJSON,
    ApiReleaseInfoFromJSONTyped,
    ApiReleaseInfoToJSON,
    ApiReleaseInfoToJSONTyped,
} from './ApiReleaseInfo';

/**
 * 
 * @export
 * @interface ApiPackageDetailResponse
 */
export interface ApiPackageDetailResponse {
    /**
     * 
     * @type {Array<ApiReleaseInfo>}
     * @memberof ApiPackageDetailResponse
     */
    builds?: Array<ApiReleaseInfo>;
    /**
     * 
     * @type {string}
     * @memberof ApiPackageDetailResponse
     */
    group?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiPackageDetailResponse
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiPackageDetailResponse
     */
    version?: string;
}

/**
 * Check if a given object implements the ApiPackageDetailResponse interface.
 */
export function instanceOfApiPackageDetailResponse(value: object): value is ApiPackageDetailResponse {
    return true;
}

export function ApiPackageDetailResponseFromJSON(json: any): ApiPackageDetailResponse {
    return ApiPackageDetailResponseFromJSONTyped(json, false);
}

export function ApiPackageDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiPackageDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'builds': json['builds'] == null ? undefined : ((json['builds'] as Array<any>).map(ApiReleaseInfoFromJSON)),
        'group': json['group'] == null ? undefined : json['group'],
        'name': json['name'] == null ? undefined : json['name'],
        'version': json['version'] == null ? undefined : json['version'],
    };
}

export function ApiPackageDetailResponseToJSON(json: any): ApiPackageDetailResponse {
    return ApiPackageDetailResponseToJSONTyped(json, false);
}

export function ApiPackageDetailResponseToJSONTyped(value?: ApiPackageDetailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'builds': value['builds'] == null ? undefined : ((value['builds'] as Array<any>).map(ApiReleaseInfoToJSON)),
        'group': value['group'],
        'name': value['name'],
        'version': value['version'],
    };
}

