/* tslint:disable */
/* eslint-disable */
/**
 * ContentSourcesBackend
 * The API for the repositories of the content sources that you can use to create and manage repositories between third-party applications and the [Red Hat Hybrid Cloud Console](https://console.redhat.com). With these repositories, you can build and deploy images using Image Builder for Cloud, on-Premise, and Edge. You can handle tasks, search for required RPMs, fetch a GPGKey from the URL, and list the features within applications. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiRepositoryEnvironment
 */
export interface ApiRepositoryEnvironment {
    /**
     * The environment description
     * @type {string}
     * @memberof ApiRepositoryEnvironment
     */
    description?: string;
    /**
     * The environment ID
     * @type {string}
     * @memberof ApiRepositoryEnvironment
     */
    id?: string;
    /**
     * The environment name
     * @type {string}
     * @memberof ApiRepositoryEnvironment
     */
    name?: string;
    /**
     * Identifier of the environment
     * @type {string}
     * @memberof ApiRepositoryEnvironment
     */
    uuid?: string;
}

/**
 * Check if a given object implements the ApiRepositoryEnvironment interface.
 */
export function instanceOfApiRepositoryEnvironment(value: object): value is ApiRepositoryEnvironment {
    return true;
}

export function ApiRepositoryEnvironmentFromJSON(json: any): ApiRepositoryEnvironment {
    return ApiRepositoryEnvironmentFromJSONTyped(json, false);
}

export function ApiRepositoryEnvironmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiRepositoryEnvironment {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
    };
}

export function ApiRepositoryEnvironmentToJSON(json: any): ApiRepositoryEnvironment {
    return ApiRepositoryEnvironmentToJSONTyped(json, false);
}

export function ApiRepositoryEnvironmentToJSONTyped(value?: ApiRepositoryEnvironment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'id': value['id'],
        'name': value['name'],
        'uuid': value['uuid'],
    };
}

