/* tslint:disable */
/* eslint-disable */
/**
 * ContentSourcesBackend
 * The API for the repositories of the content sources that you can use to create and manage repositories between third-party applications and the [Red Hat Hybrid Cloud Console](https://console.redhat.com). With these repositories, you can build and deploy images using Image Builder for Cloud, on-Premise, and Edge. You can handle tasks, search for required RPMs, fetch a GPGKey from the URL, and list the features within applications. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiTaskInfoResponse } from './ApiTaskInfoResponse';
import {
    ApiTaskInfoResponseFromJSON,
    ApiTaskInfoResponseFromJSONTyped,
    ApiTaskInfoResponseToJSON,
    ApiTaskInfoResponseToJSONTyped,
} from './ApiTaskInfoResponse';
import type { ApiSnapshotResponse } from './ApiSnapshotResponse';
import {
    ApiSnapshotResponseFromJSON,
    ApiSnapshotResponseFromJSONTyped,
    ApiSnapshotResponseToJSON,
    ApiSnapshotResponseToJSONTyped,
} from './ApiSnapshotResponse';

/**
 * 
 * @export
 * @interface ApiRepositoryImportResponse
 */
export interface ApiRepositoryImportResponse {
    /**
     * Account ID of the owner
     * @type {string}
     * @memberof ApiRepositoryImportResponse
     */
    readonly accountId?: string;
    /**
     * Content Type (rpm) of the repository
     * @type {string}
     * @memberof ApiRepositoryImportResponse
     */
    contentType?: string;
    /**
     * Architecture to restrict client usage to
     * @type {string}
     * @memberof ApiRepositoryImportResponse
     */
    distributionArch?: string;
    /**
     * Versions to restrict client usage to
     * @type {Array<string>}
     * @memberof ApiRepositoryImportResponse
     */
    distributionVersions?: Array<string>;
    /**
     * Extended release type (eus, e4s)
     * @type {string}
     * @memberof ApiRepositoryImportResponse
     */
    extendedRelease?: string;
    /**
     * Extended release version (9.4, 9.6, etc.)
     * @type {string}
     * @memberof ApiRepositoryImportResponse
     */
    extendedReleaseVersion?: string;
    /**
     * Number of consecutive failed introspections
     * @type {number}
     * @memberof ApiRepositoryImportResponse
     */
    failedIntrospectionsCount?: number;
    /**
     * Number of consecutive failed snapshots
     * @type {number}
     * @memberof ApiRepositoryImportResponse
     */
    failedSnapshotCount?: number;
    /**
     * The feature name this repo requires
     * @type {string}
     * @memberof ApiRepositoryImportResponse
     */
    featureName?: string;
    /**
     * GPG key for repository
     * @type {string}
     * @memberof ApiRepositoryImportResponse
     */
    gpgKey?: string;
    /**
     * Label used to configure the yum repository on clients
     * @type {string}
     * @memberof ApiRepositoryImportResponse
     */
    label?: string;
    /**
     * Error of last attempted introspection
     * @type {string}
     * @memberof ApiRepositoryImportResponse
     */
    lastIntrospectionError?: string;
    /**
     * Status of last introspection
     * @type {string}
     * @memberof ApiRepositoryImportResponse
     */
    lastIntrospectionStatus?: string;
    /**
     * Timestamp of last attempted introspection
     * @type {string}
     * @memberof ApiRepositoryImportResponse
     */
    lastIntrospectionTime?: string;
    /**
     * Latest Snapshot taken
     * @type {ApiSnapshotResponse}
     * @memberof ApiRepositoryImportResponse
     */
    lastSnapshot?: ApiSnapshotResponse;
    /**
     * Last snapshot task response (contains last snapshot status)
     * @type {ApiTaskInfoResponse}
     * @memberof ApiRepositoryImportResponse
     */
    lastSnapshotTask?: ApiTaskInfoResponse;
    /**
     * UUID of the last snapshot task
     * @type {string}
     * @memberof ApiRepositoryImportResponse
     */
    lastSnapshotTaskUuid?: string;
    /**
     * UUID of the last dao.Snapshot
     * @type {string}
     * @memberof ApiRepositoryImportResponse
     */
    lastSnapshotUuid?: string;
    /**
     * Timestamp of last successful introspection
     * @type {string}
     * @memberof ApiRepositoryImportResponse
     */
    lastSuccessIntrospectionTime?: string;
    /**
     * Timestamp of last introspection that had updates
     * @type {string}
     * @memberof ApiRepositoryImportResponse
     */
    lastUpdateIntrospectionTime?: string;
    /**
     * Latest URL for the snapshot distribution
     * @type {string}
     * @memberof ApiRepositoryImportResponse
     */
    latestSnapshotUrl?: string;
    /**
     * Verify packages
     * @type {boolean}
     * @memberof ApiRepositoryImportResponse
     */
    metadataVerification?: boolean;
    /**
     * Disable modularity filtering on this repository
     * @type {boolean}
     * @memberof ApiRepositoryImportResponse
     */
    moduleHotfixes?: boolean;
    /**
     * Name of the remote yum repository
     * @type {string}
     * @memberof ApiRepositoryImportResponse
     */
    name?: string;
    /**
     * Organization ID of the owner
     * @type {string}
     * @memberof ApiRepositoryImportResponse
     */
    readonly orgId?: string;
    /**
     * Origin of the repository
     * @type {string}
     * @memberof ApiRepositoryImportResponse
     */
    origin?: string;
    /**
     * Number of packages last read in the repository
     * @type {number}
     * @memberof ApiRepositoryImportResponse
     */
    packageCount?: number;
    /**
     * Enable snapshotting and hosting of this repository
     * @type {boolean}
     * @memberof ApiRepositoryImportResponse
     */
    snapshot?: boolean;
    /**
     * Combined status of last introspection and snapshot of repository (Valid, Invalid, Unavailable, Pending)
     * @type {string}
     * @memberof ApiRepositoryImportResponse
     */
    status?: string;
    /**
     * URL of the remote yum repository
     * @type {string}
     * @memberof ApiRepositoryImportResponse
     */
    url?: string;
    /**
     * UUID of the object
     * @type {string}
     * @memberof ApiRepositoryImportResponse
     */
    readonly uuid?: string;
    /**
     * Warnings to alert user of mismatched fields if there is an existing repo with the same URL
     * @type {Array<{ [key: string]: any; }>}
     * @memberof ApiRepositoryImportResponse
     */
    warnings?: Array<{ [key: string]: any; }>;
}

/**
 * Check if a given object implements the ApiRepositoryImportResponse interface.
 */
export function instanceOfApiRepositoryImportResponse(value: object): value is ApiRepositoryImportResponse {
    return true;
}

export function ApiRepositoryImportResponseFromJSON(json: any): ApiRepositoryImportResponse {
    return ApiRepositoryImportResponseFromJSONTyped(json, false);
}

export function ApiRepositoryImportResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiRepositoryImportResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['account_id'] == null ? undefined : json['account_id'],
        'contentType': json['content_type'] == null ? undefined : json['content_type'],
        'distributionArch': json['distribution_arch'] == null ? undefined : json['distribution_arch'],
        'distributionVersions': json['distribution_versions'] == null ? undefined : json['distribution_versions'],
        'extendedRelease': json['extended_release'] == null ? undefined : json['extended_release'],
        'extendedReleaseVersion': json['extended_release_version'] == null ? undefined : json['extended_release_version'],
        'failedIntrospectionsCount': json['failed_introspections_count'] == null ? undefined : json['failed_introspections_count'],
        'failedSnapshotCount': json['failed_snapshot_count'] == null ? undefined : json['failed_snapshot_count'],
        'featureName': json['feature_name'] == null ? undefined : json['feature_name'],
        'gpgKey': json['gpg_key'] == null ? undefined : json['gpg_key'],
        'label': json['label'] == null ? undefined : json['label'],
        'lastIntrospectionError': json['last_introspection_error'] == null ? undefined : json['last_introspection_error'],
        'lastIntrospectionStatus': json['last_introspection_status'] == null ? undefined : json['last_introspection_status'],
        'lastIntrospectionTime': json['last_introspection_time'] == null ? undefined : json['last_introspection_time'],
        'lastSnapshot': json['last_snapshot'] == null ? undefined : ApiSnapshotResponseFromJSON(json['last_snapshot']),
        'lastSnapshotTask': json['last_snapshot_task'] == null ? undefined : ApiTaskInfoResponseFromJSON(json['last_snapshot_task']),
        'lastSnapshotTaskUuid': json['last_snapshot_task_uuid'] == null ? undefined : json['last_snapshot_task_uuid'],
        'lastSnapshotUuid': json['last_snapshot_uuid'] == null ? undefined : json['last_snapshot_uuid'],
        'lastSuccessIntrospectionTime': json['last_success_introspection_time'] == null ? undefined : json['last_success_introspection_time'],
        'lastUpdateIntrospectionTime': json['last_update_introspection_time'] == null ? undefined : json['last_update_introspection_time'],
        'latestSnapshotUrl': json['latest_snapshot_url'] == null ? undefined : json['latest_snapshot_url'],
        'metadataVerification': json['metadata_verification'] == null ? undefined : json['metadata_verification'],
        'moduleHotfixes': json['module_hotfixes'] == null ? undefined : json['module_hotfixes'],
        'name': json['name'] == null ? undefined : json['name'],
        'orgId': json['org_id'] == null ? undefined : json['org_id'],
        'origin': json['origin'] == null ? undefined : json['origin'],
        'packageCount': json['package_count'] == null ? undefined : json['package_count'],
        'snapshot': json['snapshot'] == null ? undefined : json['snapshot'],
        'status': json['status'] == null ? undefined : json['status'],
        'url': json['url'] == null ? undefined : json['url'],
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
        'warnings': json['warnings'] == null ? undefined : json['warnings'],
    };
}

export function ApiRepositoryImportResponseToJSON(json: any): ApiRepositoryImportResponse {
    return ApiRepositoryImportResponseToJSONTyped(json, false);
}

export function ApiRepositoryImportResponseToJSONTyped(value?: Omit<ApiRepositoryImportResponse, 'account_id'|'org_id'|'uuid'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content_type': value['contentType'],
        'distribution_arch': value['distributionArch'],
        'distribution_versions': value['distributionVersions'],
        'extended_release': value['extendedRelease'],
        'extended_release_version': value['extendedReleaseVersion'],
        'failed_introspections_count': value['failedIntrospectionsCount'],
        'failed_snapshot_count': value['failedSnapshotCount'],
        'feature_name': value['featureName'],
        'gpg_key': value['gpgKey'],
        'label': value['label'],
        'last_introspection_error': value['lastIntrospectionError'],
        'last_introspection_status': value['lastIntrospectionStatus'],
        'last_introspection_time': value['lastIntrospectionTime'],
        'last_snapshot': ApiSnapshotResponseToJSON(value['lastSnapshot']),
        'last_snapshot_task': ApiTaskInfoResponseToJSON(value['lastSnapshotTask']),
        'last_snapshot_task_uuid': value['lastSnapshotTaskUuid'],
        'last_snapshot_uuid': value['lastSnapshotUuid'],
        'last_success_introspection_time': value['lastSuccessIntrospectionTime'],
        'last_update_introspection_time': value['lastUpdateIntrospectionTime'],
        'latest_snapshot_url': value['latestSnapshotUrl'],
        'metadata_verification': value['metadataVerification'],
        'module_hotfixes': value['moduleHotfixes'],
        'name': value['name'],
        'origin': value['origin'],
        'package_count': value['packageCount'],
        'snapshot': value['snapshot'],
        'status': value['status'],
        'url': value['url'],
        'warnings': value['warnings'],
    };
}

