/* tslint:disable */
/* eslint-disable */
/**
 * ContentSourcesBackend
 * The API for the repositories of the content sources that you can use to create and manage repositories between third-party applications and the [Red Hat Hybrid Cloud Console](https://console.redhat.com). With these repositories, you can build and deploy images using Image Builder for Cloud, on-Premise, and Edge. You can handle tasks, search for required RPMs, fetch a GPGKey from the URL, and list the features within applications. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiRepositoryResponse } from './ApiRepositoryResponse';
import {
    ApiRepositoryResponseFromJSON,
    ApiRepositoryResponseFromJSONTyped,
    ApiRepositoryResponseToJSON,
    ApiRepositoryResponseToJSONTyped,
} from './ApiRepositoryResponse';
import type { ApiResponseMetadata } from './ApiResponseMetadata';
import {
    ApiResponseMetadataFromJSON,
    ApiResponseMetadataFromJSONTyped,
    ApiResponseMetadataToJSON,
    ApiResponseMetadataToJSONTyped,
} from './ApiResponseMetadata';
import type { ApiLinks } from './ApiLinks';
import {
    ApiLinksFromJSON,
    ApiLinksFromJSONTyped,
    ApiLinksToJSON,
    ApiLinksToJSONTyped,
} from './ApiLinks';

/**
 * 
 * @export
 * @interface ApiRepositoryCollectionResponse
 */
export interface ApiRepositoryCollectionResponse {
    /**
     * Requested Data
     * @type {Array<ApiRepositoryResponse>}
     * @memberof ApiRepositoryCollectionResponse
     */
    data?: Array<ApiRepositoryResponse>;
    /**
     * 
     * @type {ApiLinks}
     * @memberof ApiRepositoryCollectionResponse
     */
    links?: ApiLinks;
    /**
     * 
     * @type {ApiResponseMetadata}
     * @memberof ApiRepositoryCollectionResponse
     */
    meta?: ApiResponseMetadata;
}

/**
 * Check if a given object implements the ApiRepositoryCollectionResponse interface.
 */
export function instanceOfApiRepositoryCollectionResponse(value: object): value is ApiRepositoryCollectionResponse {
    return true;
}

export function ApiRepositoryCollectionResponseFromJSON(json: any): ApiRepositoryCollectionResponse {
    return ApiRepositoryCollectionResponseFromJSONTyped(json, false);
}

export function ApiRepositoryCollectionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiRepositoryCollectionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ApiRepositoryResponseFromJSON)),
        'links': json['links'] == null ? undefined : ApiLinksFromJSON(json['links']),
        'meta': json['meta'] == null ? undefined : ApiResponseMetadataFromJSON(json['meta']),
    };
}

export function ApiRepositoryCollectionResponseToJSON(json: any): ApiRepositoryCollectionResponse {
    return ApiRepositoryCollectionResponseToJSONTyped(json, false);
}

export function ApiRepositoryCollectionResponseToJSONTyped(value?: ApiRepositoryCollectionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ApiRepositoryResponseToJSON)),
        'links': ApiLinksToJSON(value['links']),
        'meta': ApiResponseMetadataToJSON(value['meta']),
    };
}

