/* tslint:disable */
/* eslint-disable */
/**
 * ContentSourcesBackend
 * The API for the repositories of the content sources that you can use to create and manage repositories between third-party applications and the [Red Hat Hybrid Cloud Console](https://console.redhat.com). With these repositories, you can build and deploy images using Image Builder for Cloud, on-Premise, and Edge. You can handle tasks, search for required RPMs, fetch a GPGKey from the URL, and list the features within applications. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiSearchModuleStreamsRequest
 */
export interface ApiSearchModuleStreamsRequest {
    /**
     * List of rpm names to search
     * @type {Array<string>}
     * @memberof ApiSearchModuleStreamsRequest
     */
    rpmNames: Array<string>;
    /**
     * Search string to search rpm names
     * @type {string}
     * @memberof ApiSearchModuleStreamsRequest
     */
    search?: string;
    /**
     * SortBy sets the sort order of the result
     * @type {string}
     * @memberof ApiSearchModuleStreamsRequest
     */
    sortBy?: string;
    /**
     * List of repository URLs to search
     * @type {Array<string>}
     * @memberof ApiSearchModuleStreamsRequest
     */
    urls: Array<string>;
    /**
     * List of repository UUIDs to search
     * @type {Array<string>}
     * @memberof ApiSearchModuleStreamsRequest
     */
    uuids: Array<string>;
}

/**
 * Check if a given object implements the ApiSearchModuleStreamsRequest interface.
 */
export function instanceOfApiSearchModuleStreamsRequest(value: object): value is ApiSearchModuleStreamsRequest {
    if (!('rpmNames' in value) || value['rpmNames'] === undefined) return false;
    if (!('urls' in value) || value['urls'] === undefined) return false;
    if (!('uuids' in value) || value['uuids'] === undefined) return false;
    return true;
}

export function ApiSearchModuleStreamsRequestFromJSON(json: any): ApiSearchModuleStreamsRequest {
    return ApiSearchModuleStreamsRequestFromJSONTyped(json, false);
}

export function ApiSearchModuleStreamsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiSearchModuleStreamsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'rpmNames': json['rpm_names'],
        'search': json['search'] == null ? undefined : json['search'],
        'sortBy': json['sort_by'] == null ? undefined : json['sort_by'],
        'urls': json['urls'],
        'uuids': json['uuids'],
    };
}

export function ApiSearchModuleStreamsRequestToJSON(json: any): ApiSearchModuleStreamsRequest {
    return ApiSearchModuleStreamsRequestToJSONTyped(json, false);
}

export function ApiSearchModuleStreamsRequestToJSONTyped(value?: ApiSearchModuleStreamsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rpm_names': value['rpmNames'],
        'search': value['search'],
        'sort_by': value['sortBy'],
        'urls': value['urls'],
        'uuids': value['uuids'],
    };
}

