/* tslint:disable */
/* eslint-disable */
/**
 * ContentSourcesBackend
 * The API for the repositories of the content sources that you can use to create and manage repositories between third-party applications and the [Red Hat Hybrid Cloud Console](https://console.redhat.com). With these repositories, you can build and deploy images using Image Builder for Cloud, on-Premise, and Edge. You can handle tasks, search for required RPMs, fetch a GPGKey from the URL, and list the features within applications. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiSnapshotErrata } from './ApiSnapshotErrata';
import {
    ApiSnapshotErrataFromJSON,
    ApiSnapshotErrataFromJSONTyped,
    ApiSnapshotErrataToJSON,
    ApiSnapshotErrataToJSONTyped,
} from './ApiSnapshotErrata';
import type { ApiResponseMetadata } from './ApiResponseMetadata';
import {
    ApiResponseMetadataFromJSON,
    ApiResponseMetadataFromJSONTyped,
    ApiResponseMetadataToJSON,
    ApiResponseMetadataToJSONTyped,
} from './ApiResponseMetadata';
import type { ApiLinks } from './ApiLinks';
import {
    ApiLinksFromJSON,
    ApiLinksFromJSONTyped,
    ApiLinksToJSON,
    ApiLinksToJSONTyped,
} from './ApiLinks';

/**
 * 
 * @export
 * @interface ApiSnapshotErrataCollectionResponse
 */
export interface ApiSnapshotErrataCollectionResponse {
    /**
     * List of errata
     * @type {Array<ApiSnapshotErrata>}
     * @memberof ApiSnapshotErrataCollectionResponse
     */
    data?: Array<ApiSnapshotErrata>;
    /**
     * 
     * @type {ApiLinks}
     * @memberof ApiSnapshotErrataCollectionResponse
     */
    links?: ApiLinks;
    /**
     * 
     * @type {ApiResponseMetadata}
     * @memberof ApiSnapshotErrataCollectionResponse
     */
    meta?: ApiResponseMetadata;
}

/**
 * Check if a given object implements the ApiSnapshotErrataCollectionResponse interface.
 */
export function instanceOfApiSnapshotErrataCollectionResponse(value: object): value is ApiSnapshotErrataCollectionResponse {
    return true;
}

export function ApiSnapshotErrataCollectionResponseFromJSON(json: any): ApiSnapshotErrataCollectionResponse {
    return ApiSnapshotErrataCollectionResponseFromJSONTyped(json, false);
}

export function ApiSnapshotErrataCollectionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiSnapshotErrataCollectionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ApiSnapshotErrataFromJSON)),
        'links': json['links'] == null ? undefined : ApiLinksFromJSON(json['links']),
        'meta': json['meta'] == null ? undefined : ApiResponseMetadataFromJSON(json['meta']),
    };
}

export function ApiSnapshotErrataCollectionResponseToJSON(json: any): ApiSnapshotErrataCollectionResponse {
    return ApiSnapshotErrataCollectionResponseToJSONTyped(json, false);
}

export function ApiSnapshotErrataCollectionResponseToJSONTyped(value?: ApiSnapshotErrataCollectionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ApiSnapshotErrataToJSON)),
        'links': ApiLinksToJSON(value['links']),
        'meta': ApiResponseMetadataToJSON(value['meta']),
    };
}

