/* tslint:disable */
/* eslint-disable */
/**
 * ContentSourcesBackend
 * The API for the repositories of the content sources that you can use to create and manage repositories between third-party applications and the [Red Hat Hybrid Cloud Console](https://console.redhat.com). With these repositories, you can build and deploy images using Image Builder for Cloud, on-Premise, and Edge. You can handle tasks, search for required RPMs, fetch a GPGKey from the URL, and list the features within applications. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiDetectRpmsRequest
 */
export interface ApiDetectRpmsRequest {
    /**
     * Maximum number of records to return for the search
     * @type {number}
     * @memberof ApiDetectRpmsRequest
     */
    limit?: number;
    /**
     * List of rpm names to search
     * @type {Array<string>}
     * @memberof ApiDetectRpmsRequest
     */
    rpmNames?: Array<string>;
    /**
     * URLs of repositories to search
     * @type {Array<string>}
     * @memberof ApiDetectRpmsRequest
     */
    urls?: Array<string>;
    /**
     * List of repository UUIDs to search
     * @type {Array<string>}
     * @memberof ApiDetectRpmsRequest
     */
    uuids?: Array<string>;
}

/**
 * Check if a given object implements the ApiDetectRpmsRequest interface.
 */
export function instanceOfApiDetectRpmsRequest(value: object): value is ApiDetectRpmsRequest {
    return true;
}

export function ApiDetectRpmsRequestFromJSON(json: any): ApiDetectRpmsRequest {
    return ApiDetectRpmsRequestFromJSONTyped(json, false);
}

export function ApiDetectRpmsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiDetectRpmsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'limit': json['limit'] == null ? undefined : json['limit'],
        'rpmNames': json['rpm_names'] == null ? undefined : json['rpm_names'],
        'urls': json['urls'] == null ? undefined : json['urls'],
        'uuids': json['uuids'] == null ? undefined : json['uuids'],
    };
}

export function ApiDetectRpmsRequestToJSON(json: any): ApiDetectRpmsRequest {
    return ApiDetectRpmsRequestToJSONTyped(json, false);
}

export function ApiDetectRpmsRequestToJSONTyped(value?: ApiDetectRpmsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'limit': value['limit'],
        'rpm_names': value['rpmNames'],
        'urls': value['urls'],
        'uuids': value['uuids'],
    };
}

