/* tslint:disable */
/* eslint-disable */
/**
 * ContentSourcesBackend
 * The API for the repositories of the content sources that you can use to create and manage repositories between third-party applications and the [Red Hat Hybrid Cloud Console](https://console.redhat.com). With these repositories, you can build and deploy images using Image Builder for Cloud, on-Premise, and Edge. You can handle tasks, search for required RPMs, fetch a GPGKey from the URL, and list the features within applications. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiResponseMetadata } from './ApiResponseMetadata';
import {
    ApiResponseMetadataFromJSON,
    ApiResponseMetadataFromJSONTyped,
    ApiResponseMetadataToJSON,
    ApiResponseMetadataToJSONTyped,
} from './ApiResponseMetadata';
import type { ApiLinks } from './ApiLinks';
import {
    ApiLinksFromJSON,
    ApiLinksFromJSONTyped,
    ApiLinksToJSON,
    ApiLinksToJSONTyped,
} from './ApiLinks';
import type { ApiRepositoryPackageGroup } from './ApiRepositoryPackageGroup';
import {
    ApiRepositoryPackageGroupFromJSON,
    ApiRepositoryPackageGroupFromJSONTyped,
    ApiRepositoryPackageGroupToJSON,
    ApiRepositoryPackageGroupToJSONTyped,
} from './ApiRepositoryPackageGroup';

/**
 * 
 * @export
 * @interface ApiRepositoryPackageGroupCollectionResponse
 */
export interface ApiRepositoryPackageGroupCollectionResponse {
    /**
     * List of package groups
     * @type {Array<ApiRepositoryPackageGroup>}
     * @memberof ApiRepositoryPackageGroupCollectionResponse
     */
    data?: Array<ApiRepositoryPackageGroup>;
    /**
     * 
     * @type {ApiLinks}
     * @memberof ApiRepositoryPackageGroupCollectionResponse
     */
    links?: ApiLinks;
    /**
     * 
     * @type {ApiResponseMetadata}
     * @memberof ApiRepositoryPackageGroupCollectionResponse
     */
    meta?: ApiResponseMetadata;
}

/**
 * Check if a given object implements the ApiRepositoryPackageGroupCollectionResponse interface.
 */
export function instanceOfApiRepositoryPackageGroupCollectionResponse(value: object): value is ApiRepositoryPackageGroupCollectionResponse {
    return true;
}

export function ApiRepositoryPackageGroupCollectionResponseFromJSON(json: any): ApiRepositoryPackageGroupCollectionResponse {
    return ApiRepositoryPackageGroupCollectionResponseFromJSONTyped(json, false);
}

export function ApiRepositoryPackageGroupCollectionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiRepositoryPackageGroupCollectionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ApiRepositoryPackageGroupFromJSON)),
        'links': json['links'] == null ? undefined : ApiLinksFromJSON(json['links']),
        'meta': json['meta'] == null ? undefined : ApiResponseMetadataFromJSON(json['meta']),
    };
}

export function ApiRepositoryPackageGroupCollectionResponseToJSON(json: any): ApiRepositoryPackageGroupCollectionResponse {
    return ApiRepositoryPackageGroupCollectionResponseToJSONTyped(json, false);
}

export function ApiRepositoryPackageGroupCollectionResponseToJSONTyped(value?: ApiRepositoryPackageGroupCollectionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ApiRepositoryPackageGroupToJSON)),
        'links': ApiLinksToJSON(value['links']),
        'meta': ApiResponseMetadataToJSON(value['meta']),
    };
}

