/* tslint:disable */
/* eslint-disable */
/**
 * ContentSourcesBackend
 * The API for the repositories of the content sources that you can use to create and manage repositories between third-party applications and the [Red Hat Hybrid Cloud Console](https://console.redhat.com). With these repositories, you can build and deploy images using Image Builder for Cloud, on-Premise, and Edge. You can handle tasks, search for required RPMs, fetch a GPGKey from the URL, and list the features within applications. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiSnapshotRpm
 */
export interface ApiSnapshotRpm {
    /**
     * The architecture of the rpm
     * @type {string}
     * @memberof ApiSnapshotRpm
     */
    arch?: string;
    /**
     * The epoch of the rpm
     * @type {string}
     * @memberof ApiSnapshotRpm
     */
    epoch?: string;
    /**
     * The rpm package name
     * @type {string}
     * @memberof ApiSnapshotRpm
     */
    name?: string;
    /**
     * The release of the rpm
     * @type {string}
     * @memberof ApiSnapshotRpm
     */
    release?: string;
    /**
     * The summary of the rpm
     * @type {string}
     * @memberof ApiSnapshotRpm
     */
    summary?: string;
    /**
     * The version of the  rpm
     * @type {string}
     * @memberof ApiSnapshotRpm
     */
    version?: string;
}

/**
 * Check if a given object implements the ApiSnapshotRpm interface.
 */
export function instanceOfApiSnapshotRpm(value: object): value is ApiSnapshotRpm {
    return true;
}

export function ApiSnapshotRpmFromJSON(json: any): ApiSnapshotRpm {
    return ApiSnapshotRpmFromJSONTyped(json, false);
}

export function ApiSnapshotRpmFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiSnapshotRpm {
    if (json == null) {
        return json;
    }
    return {
        
        'arch': json['arch'] == null ? undefined : json['arch'],
        'epoch': json['epoch'] == null ? undefined : json['epoch'],
        'name': json['name'] == null ? undefined : json['name'],
        'release': json['release'] == null ? undefined : json['release'],
        'summary': json['summary'] == null ? undefined : json['summary'],
        'version': json['version'] == null ? undefined : json['version'],
    };
}

export function ApiSnapshotRpmToJSON(json: any): ApiSnapshotRpm {
    return ApiSnapshotRpmToJSONTyped(json, false);
}

export function ApiSnapshotRpmToJSONTyped(value?: ApiSnapshotRpm | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'arch': value['arch'],
        'epoch': value['epoch'],
        'name': value['name'],
        'release': value['release'],
        'summary': value['summary'],
        'version': value['version'],
    };
}

