# https://docs.docker.com/compose/compose-file/compose-file-v3/
version: '3'
services:
  postgres-content:
    image: "docker.io/library/postgres:14"
    ports:
      - ${CONTENT_DATABASE_PORT:-5433}:5432
    environment:
      POSTGRES_USER: ${CONTENT_DATABASE_USER:-content}
      POSTGRES_PASSWORD: ${CONTENT_DATABASE_PASSWORD:-content}
      POSTGRES_DB: ${CONTENT_DATABASE_NAME:-content}
      POSTGRES_INITDB_ARGS: '--auth-host=scram-sha-256'
      POSTGRES_HOST_AUTH_METHOD: 'scram-sha-256'
    volumes:
        - database:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready
      interval: 5s
      retries: 10
      timeout: 3s

  zookeeper:
    image: localhost/kafka:latest
    build:
      dockerfile: ./compose_files/kafka/Dockerfile
      context: ..
    command: /opt/kafka/scripts/zookeeper-entrypoint.sh
    ports:
      - "8778:8778"
      - "2181:2181"
    environment:
      ZOOKEEPER_OPTS: "-Dzookeeper.4lw.commands.whitelist=*"
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_CLIENT_PORT}
    volumes:
      - zookeeper:/tmp/zookeeper:z
      - ${KAFKA_CONFIG_DIR}:/tmp/config:z
    healthcheck:
      test: /opt/kafka/scripts/zookeeper-healthcheck.sh
      interval: 5s
      retries: 10
      timeout: 3s
      start_period: 3s

  kafka:
    image: localhost/kafka:latest
    build:
      dockerfile: ./compose_files/kafka/Dockerfile
      context: ..
    command: /opt/kafka/scripts/kafka-entrypoint.sh
    ports:
      - "9092:9092"
    restart: "on-failure:5"
    depends_on:
      - zookeeper
    volumes:
      - ${KAFKA_CONFIG_DIR}:/tmp/config:z
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_CLIENT_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OPTS: '-javaagent:/usr/jolokia/agents/jolokia-jvm.jar=host=0.0.0.0'
      KAFKA_TOPICS: "${KAFKA_TOPICS}"

volumes:
  database:
  zookeeper: