# https://docs.docker.com/compose/compose-file/compose-file-v3/
version: '3'
services:
  postgres-content:
    image: "docker.io/library/postgres:15"
    ports:
      - ${CONTENT_DATABASE_PORT:-5433}:5432
    environment:
      POSTGRES_USER: ${CONTENT_DATABASE_USER:-content}
      POSTGRES_PASSWORD: ${CONTENT_DATABASE_PASSWORD:-content}
      POSTGRES_DB: ${CONTENT_DATABASE_NAME:-content}
      POSTGRES_MULTIPLE_DATABASES: candlepin
      POSTGRES_INITDB_ARGS: '--auth-host=scram-sha-256'
      POSTGRES_HOST_AUTH_METHOD: 'scram-sha-256'
    volumes:
        - ../compose_files/postgres/init.d/:/docker-entrypoint-initdb.d:z
        - database:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready
      interval: 5s
      retries: 10
      timeout: 3s
  candlepin:
    image: quay.io/candlepin/candlepin:dev-latest
    ports:
      - 8181:8080
    environment:
      JPA_CONFIG_HIBERNATE_CONNECTION_URL: jdbc:postgresql://postgres-content/candlepin
    depends_on:
      - postgres-content
  kafka:
    image: docker.io/apache/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://:19092,CONTROLLER://:9093,PLAINTEXT_HOST://:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:19092,PLAINTEXT_HOST://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
  redis-content:
    image: docker.io/redis
    ports:
      - "6379:6379"
volumes:
  database:
  zookeeper:
