apiVersion: v1
kind: Template
metadata:
  name: content-sources-jobs
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: ClowdJobInvocation
    metadata:
      labels:
        app: content-sources-backend
      name: set-domain-label-2025-03-25
    spec:
      appName: content-sources-backend
      jobs:
        - set-domain-label
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: ClowdJobInvocation
    metadata:
      labels:
        app: content-sources-backend
      name: transform-pulp-logs-fix-2025-05
    spec:
      appName: content-sources-backend
      jobs:
        - transform-pulp-logs-fix-2025-05