apiVersion: v1
kind: Template
metadata:
  name: content-sources-jobs 
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdJobInvocation
  metadata:
    labels:
      app: content-sources-backend 
    name: rename-domains-10-25-2024
  spec:
    appName: content-sources-backend 
    jobs:
      - rename-domains

