apiVersion: v1
kind: Template
metadata:
  name: content-sources-jobs
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: ClowdJobInvocation
    metadata:
      labels:
        app: content-sources-backend
      name: set-domain-label-2025-03-25
    spec:
      appName: content-sources-backend
      jobs:
        - set-domain-label
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: ClowdJobInvocation
    metadata:
      labels:
        app: content-sources-backend
      name: hotfix-transform-pulp-logs-fix-2025-05-04
    spec:
      appName: content-sources-backend
      jobs:
        - hotfix-transform-pulp-logs-fix
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: ClowdJobInvocation
    metadata:
      labels:
        app: content-sources-backend
      name: set-detected-os-versions-2025-10-06
    spec:
      appName: content-sources-backend
      jobs:
        - set-detected-os-versions
