apiVersion: v1
kind: Template
metadata:
  name: content-sources-jobs 
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdJobInvocation
  metadata:
    labels:
      app: content-sources-backend 
    name: update-hrefs-2024-02-07
  spec:
    appName: content-sources-backend 
    jobs:
      - update-hrefs
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdJobInvocation
  metadata:
    labels:
      app: content-sources-backend
    name: repair-redhat-2023-11-30
  spec:
    appName: content-sources-backend
    jobs:
      - repair-redhat
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdJobInvocation
  metadata:
    labels:
      app: content-sources-backend
    name: retry-failed-tasks-2024-02-01
  spec:
    appName: content-sources-backend
    jobs:
      - retry-failed-tasks
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdJobInvocation
  metadata:
    labels:
      app: content-sources-backend
    name: create-latest-distributions-2024-11-27
  spec:
    appName: content-sources-backend
    jobs:
      - create-latest-distributions
