---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: content-sources-stage-test-job-${IMAGE_TAG}-${UID}
  ignore-check.kube-linter.io/no-liveness-probe: probes not required on Job
  ignore-check.kube-linter.io/no-readiness-probe: probes not required on Job
objects:
- apiVersion: batch/v1
  kind: Job
  spec:
    template:
      spec:
        # TODO Selenium container spec
        containers:
        - args:
          - run
          # This is pretty ugly, envFrom and a configmap in namespace would be a lot cleaner
          env:
          - name: ENV_FOR_DYNACONF
            value: ${ENV_FOR_DYNACONF}
          - name: IQE_PLUGINS
            value: ${IQE_PLUGINS}
          - name: IQE_MARKER_EXPRESSION
            value: ${IQE_MARKER_EXPRESSION}
          - name: IQE_FILTER_EXPRESSION
            value: ${IQE_FILTER_EXPRESSION}
          - name: IQE_LOG_LEVEL
            value: ${IQE_LOG_LEVEL}
          - name: IQE_REQUIREMENTS
            value: ${IQE_REQUIREMENTS}
          - name: IQE_REQUIREMENTS_PRIORITY
            value: ${IQE_REQUIREMENTS_PRIORITY}
          - name: IQE_TEST_IMPORTANCE
            value: ${IQE_TEST_IMPORTANCE}
          - name: DYNACONF_IQE_VAULT_LOADER_ENABLED
            value: "true"
          - name: DYNACONF_IQE_VAULT_VERIFY
            value: "true"
          - name: DYNACONF_IQE_VAULT_URL
            valueFrom:
              secretKeyRef:
                key: url
                name: iqe-vault
                optional: true
          - name: DYNACONF_IQE_VAULT_MOUNT_POINT
            valueFrom:
              secretKeyRef:
                key: mountPoint
                name: iqe-vault
                optional: true
          - name: DYNACONF_IQE_VAULT_ROLE_ID
            valueFrom:
              secretKeyRef:
                key: roleId
                name: iqe-vault
                optional: true
          - name: DYNACONF_IQE_VAULT_SECRET_ID
            valueFrom:
              secretKeyRef:
                key: secretId
                name: iqe-vault
                optional: true
          image: ${IQE_IMAGE}
          imagePullPolicy: Always
          imagePullSecrets:
          - quay-cloudservices-pull
          name: content-sources-stage-post-deploy-tests-${UID}
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Never
        schedulerName: default-scheduler
    metadata:
      annotations:
        name: content-sources-stage-test-internal-${IMAGE_TAG}-${UID}
        ignore-check.kube-linter.io/no-liveness-probe: probes not required on Job pods
        ignore-check.kube-linter.io/no-readiness-probe: probes not required on Job pods

parameters:
- name: IMAGE_TAG
  value: ''
  required: true
- name: UID
  description: "Unique job name suffix"
  generate: expression
  from: "[a-z0-9]{6}"
- name: IQE_IMAGE
  description: "container image path for the iqe plugin"
  value: quay.io/cloudservices/iqe-tests:content_sources
- name: ENV_FOR_DYNACONF
  value: stage_proxy
- name: IQE_PLUGINS
  value: content_sources
- name: IQE_MARKER_EXPRESSION
  value: stage
- name: IQE_FILTER_EXPRESSION
  value: ''
- name: IQE_LOG_LEVEL
  value: info
- name: IQE_REQUIREMENTS
  value: ''
- name: IQE_REQUIREMENTS_PRIORITY
  value: ''
- name: IQE_TEST_IMPORTANCE
  value: ''

  
