---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: content-sources-${NAME_STUB}
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: content-sources-${NAME_STUB}-${UID}
    annotations:
      "ignore-check.kube-linter.io/no-liveness-probe": "probes not required on Job pods"
      "ignore-check.kube-linter.io/no-readiness-probe": "probes not required on Job pods"
    labels:
      image-tag: ${IMAGE_TAG}
      iqe-image-tag: ${IQE_IMAGE_TAG}
      iqe-env: ${ENV_FOR_DYNACONF}
      iqe-plugin: ${IQE_PLUGINS}
  spec:
    backoffLimit: 0
    template:
      spec:
        imagePullSecrets:
        - name: quay-cloudservices-pull
        restartPolicy: Never
        containers:
        - name: content-sources-${NAME_STUB}-${IMAGE_TAG}-${UID}
          image: ${IQE_IMAGE}:${IQE_IMAGE_TAG}
          imagePullPolicy: Always
          args:
          - run
          env:
          - name: ENV_FOR_DYNACONF
            value: ${ENV_FOR_DYNACONF}
          - name: DYNACONF_MAIN__use_beta
            value: ${USE_BETA}
          - name: IQE_IBUTSU_SOURCE
            value: content-sources-saas-${IMAGE_TAG}-${UID}
          - name: IQE_NETLOG
            value: ${IQE_NETLOG}
          - name: IQE_PLUGINS
            value: ${IQE_PLUGINS}
          - name: IQE_MARKER_EXPRESSION
            value: ${IQE_MARKER_EXPRESSION}
          - name: IQE_FILTER_EXPRESSION
            value: ${IQE_FILTER_EXPRESSION}
          - name: IQE_LOG_LEVEL
            value: ${IQE_LOG_LEVEL}
          - name: IQE_REQUIREMENTS
            value: ${IQE_REQUIREMENTS}
          - name: IQE_REQUIREMENTS_PRIORITY
            value: ${IQE_REQUIREMENTS_PRIORITY}
          - name: IQE_TEST_IMPORTANCE
            value: ${IQE_TEST_IMPORTANCE}
          - name: IQE_PARALLEL_ENABLED
            value: ${IQE_PARALLEL_ENABLED}
          - name: DYNACONF_IQE_VAULT_LOADER_ENABLED
            value: "true"
          - name: DYNACONF_IQE_VAULT_VERIFY
            value: "true"
          - name: DYNACONF_IQE_VAULT_URL
            valueFrom:
              secretKeyRef:
                key: url
                name: iqe-vault
                optional: true
          - name: DYNACONF_IQE_VAULT_MOUNT_POINT
            valueFrom:
              secretKeyRef:
                key: mountPoint
                name: iqe-vault
                optional: true
          - name: DYNACONF_IQE_VAULT_ROLE_ID
            valueFrom:
              secretKeyRef:
                key: roleId
                name: iqe-vault
                optional: true
          - name: DYNACONF_IQE_VAULT_SECRET_ID
            valueFrom:
              secretKeyRef:
                key: secretId
                name: iqe-vault
                optional: true
          resources:
            limits:
              cpu: "1"
              memory: 1.5Gi
            requests:
              cpu: 250m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
parameters:
- name: IMAGE_TAG
  value: ''
  required: false
  description: Optional app image tag for labeling
- name: UID
  description: "Unique job name suffix"
  generate: expression
  from: "[a-z0-9]{6}"
- name: IQE_IMAGE
- name: IQE_REQUIREMENTS
  value: ''
- name: IQE_REQUIREMENTS_PRIORITY
  value: ''
- name: IQE_TEST_IMPORTANCE
  value: ''
- name: IQE_NETLOG
  value: "1"
  description: Enable HTTP network logging in IQE (keep for API debugging)
- name: NAME_STUB
  value: 'e2e-tests'
- name: IQE_PARALLEL_ENABLED
  value: "false"
