version: 2
updates:
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Build: "
    ignore:
      - dependency-name: "go"
        versions:
          - ">=1.26"
    groups:
      go:
        patterns:
          - "*"
