# Configuration for golangci-lint. See https://golangci-lint.run/usage/configuration/.
linters:
  disable-all: false # use default linters
  enable:
    - gofmt
    - whitespace
    - govet
    - misspell
    - forcetypeassert
    - gci
    - bodyclose
    - gosec
linters-settings:
  gosec:
    excludes:
      - G404 # we want to use pseudo-random numbers in some cases, so this should be excluded
issues:
  exclude:
    - composite
