filename: "{{ .SrcPackageName | snakecase }}_mock.go"
dir: '{{ .InterfaceDir }}'
structname: Mock{{ .InterfaceName }}
pkgname: '{{ .SrcPackageName }}'
template: testify
template-data:
  unroll-variadic: true

packages:
  github.com/content-services/content-sources-backend/pkg/cache:
    interfaces:
      Cache: {}
  github.com/content-services/content-sources-backend/pkg/clients/candlepin_client:
    interfaces:
      CandlepinClient: {}
  github.com/content-services/content-sources-backend/pkg/clients/feature_service_client:
    interfaces:
      FeatureServiceClient: {}
  github.com/content-services/content-sources-backend/pkg/clients/pulp_client:
    interfaces:
      PulpClient: {}
      PulpGlobalClient: {}
  github.com/content-services/content-sources-backend/pkg/clients/roadmap_client:
    interfaces:
      RoadmapClient: {}
  github.com/content-services/content-sources-backend/pkg/dao:
    interfaces:
      AdminTaskDao: {}
      DomainDao: {}
      EnvironmentDao: {}
      MetricsDao: {}
      ModuleStreamDao: {}
      PackageGroupDao: {}
      RepositoryConfigDao: {}
      RepositoryDao: {}
      RpmDao: {}
      SnapshotDao: {}
      TaskInfoDao: {}
      TemplateDao: {}
  github.com/content-services/content-sources-backend/pkg/tasks/client:
    interfaces:
      TaskClient: {}
  github.com/content-services/content-sources-backend/pkg/tasks/queue:
    interfaces:
      Queue: {}
