filename: "{{ .InterfaceName | snakecase }}_mock.go"
dir: "{{.InterfaceDir}}"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
inpackage: True
with-expecter: False
disable-version-string: True

packages:
  github.com/content-services/content-sources-backend/pkg/tasks/queue:
    interfaces:
      Queue:
  github.com/content-services/content-sources-backend/pkg/tasks/client:
    interfaces:
      TaskClient:
        config:
          filename: "client_mock.go"
  github.com/content-services/content-sources-backend/pkg/pulp_client:
    interfaces:
      PulpGlobalClient:
      PulpClient:
  github.com/content-services/content-sources-backend/pkg/candlepin_client:
    interfaces:
      CandlepinClient:
  github.com/content-services/content-sources-backend/pkg/cache:
    interfaces:
      Cache:
  github.com/content-services/content-sources-backend/pkg/dao:
    interfaces:
      RepositoryConfigDao:
        config:
          filename: "repository_configs_mock.go"
      RpmDao:
        config:
          filename: "rpms_mock.go"
      RepositoryDao:
        config:
          filename: "repositories_mock.go"
      SnapshotDao:
        config:
          filename: "snapshots_mock.go"
      MetricsDao:
        config:
          filename: "metrics_mock.go"
      TaskInfoDao:
        config:
          filename: "task_info_mock.go"
      AdminTaskDao:
        config:
          filename: "admin_tasks_mock.go"
      DomainDao:
        config:
          filename: "domain_dao_mock.go"
      PackageGroupDao:
        config:
          filename: "package_groups_mock.go"
      EnvironmentDao:
        config:
          filename: "environments_mock.go"
      TemplateDao:
        config:
          filename: "templates_mock.go"
      ModuleStreamsDao:
        config:
          filename: "modules_streams_mock.go"
