# curl http://localhost:8000/api/content-sources/v1.0/repositories/  	-H "Content-Type: application/json" 	-d '{"name":"sample zoo","url":"https://jlsherrill.fedorapeople.org/fake-repos/needed-errata/","snapshot": false}'
POST http://localhost:8000/api/content-sources/v1.0/repositories/bulk_create/
Content-Type: application/json
x-rh-identity: eyJpZGVudGl0eSI6eyJ0eXBlIjoiVXNlciIsInVzZXIiOnsidXNlcm5hbWUiOiJqZG9lIn0sImludGVybmFsIjp7Im9yZ19pZCI6IjEyMyJ9fX0K
x-Rh-Insights-Request-Id: 12345

[{"name":"sample zoo6","url":"https://dl.fedoraproject.org/pub/epel/9/Everything/x86_64/"}]

###


#POST http://localhost:8000/api/content-sources/v1.0/repositories/
#Content-Type: application/json
#x-rh-identity: eyJpZGVudGl0eSI6eyJ0eXBlIjoiVXNlciIsInVzZXIiOnsidXNlcm5hbWUiOiJmb28ifSwiYWNjb3VudF9udW1iZXIiOiIzNCIsImludGVybmFsIjp7Im9yZ19pZCI6IjM0In19fQo==
#
#{"name":"epel","url":"https://dl.fedoraproject.org/pub/epel/9/Everything/x86_64/","snapshot": true}
#
####

POST http://localhost:8000/api/content-sources/v1.0/repositories/
Content-Type: application/json
x-rh-identity: eyJpZGVudGl0eSI6eyJ0eXBlIjoiVXNlciIsInVzZXIiOnsidXNlcm5hbWUiOiIxIn0sImFjY291bnRfbnVtYmVyIjoiMSIsImludGVybmFsIjp7Im9yZ19pZCI6IjEifX19Cg==
x-Rh-Insights-Request-Id: 9876


{
  "name": "zoom16z",
  "url": "https://download-i2.fedoraproject.org/pub/epel/9/Everything/x86_64/",
  "snapshot": false
}


####
POST http://localhost:8000/api/content-sources/v1.0/repositories/
Content-Type: application/json
x-rh-identity: eyJpZGVudGl0eSI6eyJ0eXBlIjoiVXNlciIsInVzZXIiOnsidXNlcm5hbWUiOiIxIn0sImFjY291bnRfbnVtYmVyIjoiMSIsImludGVybmFsIjp7Im9yZ19pZCI6IjEifX19Cg==
x-Rh-Insights-Request-Id: 9876


{
  "name": "pulp3.16",
  "url": "http://yum.theforeman.org/pulpcore/3.16/el8/x86_64/",
  "snapshot": true
}




####

POST http://localhost:8000/api/content-sources/v1.0/repositories/
Content-Type: application/json
x-rh-identity: eyJpZGVudGl0eSI6eyJ0eXBlIjoiVXNlciIsInVzZXIiOnsidXNlcm5hbWUiOiIxIn0sImFjY291bnRfbnVtYmVyIjoiMSIsImludGVybmFsIjp7Im9yZ19pZCI6IjEifX19Cg==
x-Rh-Insights-Request-Id: 9876


{
  "name": "zipbomb2",
  "url": "http://localhost/zipbomb",
  "snapshot": false
}



#### Cancel

POST http://localhost:8000/api/content-sources/v1.0/tasks/44729d18-7358-4bc1-b18a-c8de4101f647/cancel/
Content-Type: application/json
x-rh-identity: eyJpZGVudGl0eSI6eyJ0eXBlIjoiVXNlciIsInVzZXIiOnsidXNlcm5hbWUiOiIxIn0sImFjY291bnRfbnVtYmVyIjoiMSIsImludGVybmFsIjp7Im9yZ19pZCI6IjEifX19Cg==
x-Rh-Insights-Request-Id: 9876


#### Get

GET http://localhost:8000/api/content-sources/v1.0/repositories/
Content-Type: application/json
x-rh-identity: eyJpZGVudGl0eSI6eyJ0eXBlIjoiVXNlciIsInVzZXIiOnsidXNlcm5hbWUiOiIxIn0sImFjY291bnRfbnVtYmVyIjoiMSIsImludGVybmFsIjp7Im9yZ19pZCI6IjEifX19Cg==
x-Rh-Insights-Request-Id: 9876



###

POST http://localhost:8000/api/content-sources/v1.0/repositories/bulk_delete/
Content-Type: application/json
x-rh-identity: eyJpZGVudGl0eSI6eyJ0eXBlIjoiVXNlciIsInVzZXIiOnsidXNlcm5hbWUiOiIxIn0sImFjY291bnRfbnVtYmVyIjoiMSIsImludGVybmFsIjp7Im9yZ19pZCI6IjEifX19Cg==


{"uuids": ["472a4a38-a75f-4f9f-aea3-32a92047c3f8"]}


###

DELETE http://localhost:8000/api/content-sources/v1.0/repositories/5ef51db8-15c7-4988-b892-f7a909a084fb
Content-Type: application/json
x-rh-identity: eyJpZGVudGl0eSI6eyJ0eXBlIjoiVXNlciIsInVzZXIiOnsidXNlcm5hbWUiOiIxIn0sImFjY291bnRfbnVtYmVyIjoiMSIsImludGVybmFsIjp7Im9yZ19pZCI6IjEifX19Cg==

###


PATCH http://localhost:8000/api/content-sources/v1.0/repositories/5a7bc510-1920-496c-bb1a-77745b6987c1
Content-Type: application/json
x-rh-identity: eyJpZGVudGl0eSI6eyJ0eXBlIjoiVXNlciIsInVzZXIiOnsidXNlcm5hbWUiOiIxIn0sImFjY291bnRfbnVtYmVyIjoiMSIsImludGVybmFsIjp7Im9yZ19pZCI6IjEifX19Cg==

{"url":  "https://download-i2.fedoraproject.org/pub/epel/9/Everything/x86_64/"}

###

GET http://localhost:8000/api/content-sources/v1.0/repositories/c577cb1d-afb8-4343-a64c-88315a2a0eda
Content-Type: application/json
x-rh-identity: eyJpZGVudGl0eSI6eyJ0eXBlIjoiVXNlciIsInVzZXIiOnsidXNlcm5hbWUiOiJmb28ifSwiYWNjb3VudF9udW1iZXIiOiIzMCIsImludGVybmFsIjp7Im9yZ19pZCI6IjMwIn19fQo=
x-Rh-Insights-Request-Id: 9876


###

POST http://localhost:8000/api/content-sources/v1.0/repository_parameters/validate/
Content-Type: application/json
x-rh-identity: eyJpZGVudGl0eSI6eyJ0eXBlIjoiVXNlciIsInVzZXIiOnsidXNlcm5hbWUiOiJmb28ifSwiYWNjb3VudF9udW1iZXIiOiIzMCIsImludGVybmFsIjp7Im9yZ19pZCI6IjMwIn19fQo=

[{"url":  "http://yum.theforeman.org/pulpcore/3.16/el8/x86_64/", "uuid":  "'response.write(731,493*173,328)'", "snapshot":  true}]

###
GET http://localhost:8000/api/content-sources/v1.0/features/
Content-Type: application/json
x-rh-identity: eyJpZGVudGl0eSI6eyJ0eXBlIjoiVXNlciIsInVzZXIiOnsidXNlcm5hbWUiOiJmb28ifSwiYWNjb3VudF9udW1iZXIiOiIzMCIsImludGVybmFsIjp7Im9yZ19pZCI6IjMwIn19fQo=

###
GET http://localhost:8000/api/content-sources/v1.0/repositories/?search=zoom10
Content-Type: application/json
x-rh-identity: eyJpZGVudGl0eSI6eyJ0eXBlIjoiVXNlciIsInVzZXIiOnsidXNlcm5hbWUiOiIxIn0sImFjY291bnRfbnVtYmVyIjoiMSIsImludGVybmFsIjp7Im9yZ19pZCI6IjEifX19Cg==