// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package s3_client

import (
	"context"
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewMockS3Client creates a new instance of MockS3Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockS3Client(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockS3Client {
	mock := &MockS3Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockS3Client is an autogenerated mock type for the S3Client type
type MockS3Client struct {
	mock.Mock
}

type MockS3Client_Expecter struct {
	mock *mock.Mock
}

func (_m *MockS3Client) EXPECT() *MockS3Client_Expecter {
	return &MockS3Client_Expecter{mock: &_m.Mock}
}

// Put provides a mock function for the type MockS3Client
func (_mock *MockS3Client) Put(ctx context.Context, key string, body io.Reader) error {
	ret := _mock.Called(ctx, key, body)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Reader) error); ok {
		r0 = returnFunc(ctx, key, body)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockS3Client_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockS3Client_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - body io.Reader
func (_e *MockS3Client_Expecter) Put(ctx interface{}, key interface{}, body interface{}) *MockS3Client_Put_Call {
	return &MockS3Client_Put_Call{Call: _e.mock.On("Put", ctx, key, body)}
}

func (_c *MockS3Client_Put_Call) Run(run func(ctx context.Context, key string, body io.Reader)) *MockS3Client_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 io.Reader
		if args[2] != nil {
			arg2 = args[2].(io.Reader)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockS3Client_Put_Call) Return(err error) *MockS3Client_Put_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockS3Client_Put_Call) RunAndReturn(run func(ctx context.Context, key string, body io.Reader) error) *MockS3Client_Put_Call {
	_c.Call.Return(run)
	return _c
}
