# This file exists solely so Dependabot can track the openapi-generator-cli version.

services:
  openapi-generator:
    # Used by mk/swag.mk
    image: openapitools/openapi-generator-cli:v7.23.0@sha256:5ffccd3b0d4ac57eac443e1c9b3e2f2bb7f0a21ffe6c6701f3690d7edc78bf2d