/* tslint:disable */
/* eslint-disable */
/**
 * ContentSourcesBackend
 * The API for the repositories of the content sources that you can use to create and manage repositories between third-party applications and the [Red Hat Hybrid Cloud Console](https://console.redhat.com). With these repositories, you can build and deploy images using Image Builder for Cloud, on-Premise, and Edge. You can handle tasks, search for required RPMs, fetch a GPGKey from the URL, and list the features within applications. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ApiLightwellTokenCreateRequest,
    ApiLightwellTokenCreateRequestFromJSON,
    ApiLightwellTokenCreateRequestToJSON,
} from '../models/ApiLightwellTokenCreateRequest';
import {
    type ApiLightwellTokenResponse,
    ApiLightwellTokenResponseFromJSON,
    ApiLightwellTokenResponseToJSON,
} from '../models/ApiLightwellTokenResponse';
import {
    type ErrorsErrorResponse,
    ErrorsErrorResponseFromJSON,
    ErrorsErrorResponseToJSON,
} from '../models/ErrorsErrorResponse';

export interface CreateLightwellTokenRequest {
    apiLightwellTokenCreateRequest: ApiLightwellTokenCreateRequest;
}

export interface RevokeLightwellTokenRequest {
    uuid: string;
}

/**
 * 
 */
export class LightwellTokensApi extends runtime.BaseAPI {

    /**
     * Creates request options for createLightwellToken without sending the request
     */
    async createLightwellTokenRequestOpts(requestParameters: CreateLightwellTokenRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['apiLightwellTokenCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'apiLightwellTokenCreateRequest',
                'Required parameter "apiLightwellTokenCreateRequest" was null or undefined when calling createLightwellToken().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/tokens/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApiLightwellTokenCreateRequestToJSON(requestParameters['apiLightwellTokenCreateRequest']),
        };
    }

    /**
     * Create a personal Lightwell access token. Only org admins may create tokens. The plaintext token is returned once.
     * Create a Lightwell access token
     */
    async createLightwellTokenRaw(requestParameters: CreateLightwellTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiLightwellTokenResponse>> {
        const requestOptions = await this.createLightwellTokenRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiLightwellTokenResponseFromJSON(jsonValue));
    }

    /**
     * Create a personal Lightwell access token. Only org admins may create tokens. The plaintext token is returned once.
     * Create a Lightwell access token
     */
    async createLightwellToken(requestParameters: CreateLightwellTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiLightwellTokenResponse> {
        const response = await this.createLightwellTokenRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listLightwellTokens without sending the request
     */
    async listLightwellTokensRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/tokens/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List Lightwell access tokens for the caller\'s organization. Only org admins may list tokens.
     * List Lightwell access tokens
     */
    async listLightwellTokensRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ApiLightwellTokenResponse>>> {
        const requestOptions = await this.listLightwellTokensRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ApiLightwellTokenResponseFromJSON));
    }

    /**
     * List Lightwell access tokens for the caller\'s organization. Only org admins may list tokens.
     * List Lightwell access tokens
     */
    async listLightwellTokens(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ApiLightwellTokenResponse>> {
        const response = await this.listLightwellTokensRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for revokeLightwellToken without sending the request
     */
    async revokeLightwellTokenRequestOpts(requestParameters: RevokeLightwellTokenRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling revokeLightwellToken().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/tokens/{uuid}`;
        urlPath = urlPath.replace('{uuid}', encodeURIComponent(String(requestParameters['uuid'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Revoke a Lightwell access token by UUID. Only org admins may revoke tokens.
     * Revoke a Lightwell access token
     */
    async revokeLightwellTokenRaw(requestParameters: RevokeLightwellTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.revokeLightwellTokenRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Revoke a Lightwell access token by UUID. Only org admins may revoke tokens.
     * Revoke a Lightwell access token
     */
    async revokeLightwellToken(requestParameters: RevokeLightwellTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.revokeLightwellTokenRaw(requestParameters, initOverrides);
    }

}
