/* tslint:disable */
/* eslint-disable */
/**
 * ContentSourcesBackend
 * The API for the repositories of the content sources that you can use to create and manage repositories between third-party applications and the [Red Hat Hybrid Cloud Console](https://console.redhat.com). With these repositories, you can build and deploy images using Image Builder for Cloud, on-Premise, and Edge. You can handle tasks, search for required RPMs, fetch a GPGKey from the URL, and list the features within applications. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ApiMavenPackageDetailResponse,
    ApiMavenPackageDetailResponseFromJSON,
    ApiMavenPackageDetailResponseToJSON,
} from '../models/ApiMavenPackageDetailResponse';
import {
    type ApiMavenPackageVersionsResponse,
    ApiMavenPackageVersionsResponseFromJSON,
    ApiMavenPackageVersionsResponseToJSON,
} from '../models/ApiMavenPackageVersionsResponse';
import {
    type ApiPackageResponse,
    ApiPackageResponseFromJSON,
    ApiPackageResponseToJSON,
} from '../models/ApiPackageResponse';
import {
    type ApiPythonPackageDetailResponse,
    ApiPythonPackageDetailResponseFromJSON,
    ApiPythonPackageDetailResponseToJSON,
} from '../models/ApiPythonPackageDetailResponse';
import {
    type ApiPythonPackageVersionsResponse,
    ApiPythonPackageVersionsResponseFromJSON,
    ApiPythonPackageVersionsResponseToJSON,
} from '../models/ApiPythonPackageVersionsResponse';
import {
    type ErrorsErrorResponse,
    ErrorsErrorResponseFromJSON,
    ErrorsErrorResponseToJSON,
} from '../models/ErrorsErrorResponse';

export interface GetPackageDetailRequest {
    uuid: string;
    group: string;
    name: string;
    version: string;
}

export interface GetPythonPackageDetailRequest {
    uuid: string;
    name: string;
    version: string;
}

export interface GetPythonPackageVersionsRequest {
    uuid: string;
    name: string;
}

export interface ListMavenPackageVersionsRequest {
    uuid: string;
    group: string;
    name: string;
}

export interface ListPackagesRequest {
    uuid: string;
    offset?: number;
    limit?: number;
    search?: string;
}

/**
 * 
 */
export class PackagesApi extends runtime.BaseAPI {

    /**
     * Creates request options for getPackageDetail without sending the request
     */
    async getPackageDetailRequestOpts(requestParameters: GetPackageDetailRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling getPackageDetail().'
            );
        }

        if (requestParameters['group'] == null) {
            throw new runtime.RequiredError(
                'group',
                'Required parameter "group" was null or undefined when calling getPackageDetail().'
            );
        }

        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling getPackageDetail().'
            );
        }

        if (requestParameters['version'] == null) {
            throw new runtime.RequiredError(
                'version',
                'Required parameter "version" was null or undefined when calling getPackageDetail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/repositories/{uuid}/maven_packages/{group}/{name}/{version}`;
        urlPath = urlPath.replace('{uuid}', encodeURIComponent(String(requestParameters['uuid'])));
        urlPath = urlPath.replace('{group}', encodeURIComponent(String(requestParameters['group'])));
        urlPath = urlPath.replace('{name}', encodeURIComponent(String(requestParameters['name'])));
        urlPath = urlPath.replace('{version}', encodeURIComponent(String(requestParameters['version'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get builds for a specific Maven package by group, name, and version.
     * Get Maven Package Detail
     */
    async getPackageDetailRaw(requestParameters: GetPackageDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiMavenPackageDetailResponse>> {
        const requestOptions = await this.getPackageDetailRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiMavenPackageDetailResponseFromJSON(jsonValue));
    }

    /**
     * Get builds for a specific Maven package by group, name, and version.
     * Get Maven Package Detail
     */
    async getPackageDetail(requestParameters: GetPackageDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiMavenPackageDetailResponse> {
        const response = await this.getPackageDetailRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getPythonPackageDetail without sending the request
     */
    async getPythonPackageDetailRequestOpts(requestParameters: GetPythonPackageDetailRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling getPythonPackageDetail().'
            );
        }

        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling getPythonPackageDetail().'
            );
        }

        if (requestParameters['version'] == null) {
            throw new runtime.RequiredError(
                'version',
                'Required parameter "version" was null or undefined when calling getPythonPackageDetail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/repositories/{uuid}/python_packages/{name}/{version}`;
        urlPath = urlPath.replace('{uuid}', encodeURIComponent(String(requestParameters['uuid'])));
        urlPath = urlPath.replace('{name}', encodeURIComponent(String(requestParameters['name'])));
        urlPath = urlPath.replace('{version}', encodeURIComponent(String(requestParameters['version'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get metadata and distributions for a specific Python package by name and version.
     * Get Python Package Detail
     */
    async getPythonPackageDetailRaw(requestParameters: GetPythonPackageDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiPythonPackageDetailResponse>> {
        const requestOptions = await this.getPythonPackageDetailRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiPythonPackageDetailResponseFromJSON(jsonValue));
    }

    /**
     * Get metadata and distributions for a specific Python package by name and version.
     * Get Python Package Detail
     */
    async getPythonPackageDetail(requestParameters: GetPythonPackageDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiPythonPackageDetailResponse> {
        const response = await this.getPythonPackageDetailRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getPythonPackageVersions without sending the request
     */
    async getPythonPackageVersionsRequestOpts(requestParameters: GetPythonPackageVersionsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling getPythonPackageVersions().'
            );
        }

        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling getPythonPackageVersions().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/repositories/{uuid}/python_packages/{name}`;
        urlPath = urlPath.replace('{uuid}', encodeURIComponent(String(requestParameters['uuid'])));
        urlPath = urlPath.replace('{name}', encodeURIComponent(String(requestParameters['name'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get metadata and distributions for all versions of a Python package by name.
     * Get Python Package Versions
     */
    async getPythonPackageVersionsRaw(requestParameters: GetPythonPackageVersionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiPythonPackageVersionsResponse>> {
        const requestOptions = await this.getPythonPackageVersionsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiPythonPackageVersionsResponseFromJSON(jsonValue));
    }

    /**
     * Get metadata and distributions for all versions of a Python package by name.
     * Get Python Package Versions
     */
    async getPythonPackageVersions(requestParameters: GetPythonPackageVersionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiPythonPackageVersionsResponse> {
        const response = await this.getPythonPackageVersionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listMavenPackageVersions without sending the request
     */
    async listMavenPackageVersionsRequestOpts(requestParameters: ListMavenPackageVersionsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling listMavenPackageVersions().'
            );
        }

        if (requestParameters['group'] == null) {
            throw new runtime.RequiredError(
                'group',
                'Required parameter "group" was null or undefined when calling listMavenPackageVersions().'
            );
        }

        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling listMavenPackageVersions().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/repositories/{uuid}/maven_packages/{group}/{name}`;
        urlPath = urlPath.replace('{uuid}', encodeURIComponent(String(requestParameters['uuid'])));
        urlPath = urlPath.replace('{group}', encodeURIComponent(String(requestParameters['group'])));
        urlPath = urlPath.replace('{name}', encodeURIComponent(String(requestParameters['name'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List all versions (builds) for a specific Maven package by group and name.
     * List Maven Package Versions
     */
    async listMavenPackageVersionsRaw(requestParameters: ListMavenPackageVersionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiMavenPackageVersionsResponse>> {
        const requestOptions = await this.listMavenPackageVersionsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiMavenPackageVersionsResponseFromJSON(jsonValue));
    }

    /**
     * List all versions (builds) for a specific Maven package by group and name.
     * List Maven Package Versions
     */
    async listMavenPackageVersions(requestParameters: ListMavenPackageVersionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiMavenPackageVersionsResponse> {
        const response = await this.listMavenPackageVersionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listPackages without sending the request
     */
    async listPackagesRequestOpts(requestParameters: ListPackagesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling listPackages().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/repositories/{uuid}/packages`;
        urlPath = urlPath.replace('{uuid}', encodeURIComponent(String(requestParameters['uuid'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List packages for Maven (group and name) or Python (name) repositories. Returns empty results for other content types.
     * List Packages
     */
    async listPackagesRaw(requestParameters: ListPackagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiPackageResponse>> {
        const requestOptions = await this.listPackagesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiPackageResponseFromJSON(jsonValue));
    }

    /**
     * List packages for Maven (group and name) or Python (name) repositories. Returns empty results for other content types.
     * List Packages
     */
    async listPackages(requestParameters: ListPackagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiPackageResponse> {
        const response = await this.listPackagesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
