/* tslint:disable */
/* eslint-disable */
/**
 * ContentSourcesBackend
 * The API for the repositories of the content sources that you can use to create and manage repositories between third-party applications and the [Red Hat Hybrid Cloud Console](https://console.redhat.com). With these repositories, you can build and deploy images using Image Builder for Cloud, on-Premise, and Edge. You can handle tasks, search for required RPMs, fetch a GPGKey from the URL, and list the features within applications. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiContentUnitSearchRequest,
  ApiRepositoryPackageGroupCollectionResponse,
  ApiSearchPackageGroupResponse,
  ApiSnapshotSearchRpmRequest,
  ErrorsErrorResponse,
} from '../models/index';
import {
    ApiContentUnitSearchRequestFromJSON,
    ApiContentUnitSearchRequestToJSON,
    ApiRepositoryPackageGroupCollectionResponseFromJSON,
    ApiRepositoryPackageGroupCollectionResponseToJSON,
    ApiSearchPackageGroupResponseFromJSON,
    ApiSearchPackageGroupResponseToJSON,
    ApiSnapshotSearchRpmRequestFromJSON,
    ApiSnapshotSearchRpmRequestToJSON,
    ErrorsErrorResponseFromJSON,
    ErrorsErrorResponseToJSON,
} from '../models/index';

export interface ListRepositoriesPackageGroupsRequest {
    uuid: string;
    limit?: number;
    offset?: number;
    search?: string;
    sortBy?: string;
}

export interface SearchPackageGroupRequest {
    apiContentUnitSearchRequest: ApiContentUnitSearchRequest;
}

export interface SearchSnapshotPackageGroupsRequest {
    apiSnapshotSearchRpmRequest: ApiSnapshotSearchRpmRequest;
}

/**
 * 
 */
export class PackagegroupsApi extends runtime.BaseAPI {

    /**
     * List package groups in a repository.
     * List Repositories Package Groups
     */
    async listRepositoriesPackageGroupsRaw(requestParameters: ListRepositoriesPackageGroupsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiRepositoryPackageGroupCollectionResponse>> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling listRepositoriesPackageGroups().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['sortBy'] != null) {
            queryParameters['sort_by'] = requestParameters['sortBy'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/repositories/{uuid}/package_groups`;
        urlPath = urlPath.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiRepositoryPackageGroupCollectionResponseFromJSON(jsonValue));
    }

    /**
     * List package groups in a repository.
     * List Repositories Package Groups
     */
    async listRepositoriesPackageGroups(requestParameters: ListRepositoriesPackageGroupsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiRepositoryPackageGroupCollectionResponse> {
        const response = await this.listRepositoriesPackageGroupsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This enables users to search for package groups in a given list of repositories.
     * Search package groups
     */
    async searchPackageGroupRaw(requestParameters: SearchPackageGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ApiSearchPackageGroupResponse>>> {
        if (requestParameters['apiContentUnitSearchRequest'] == null) {
            throw new runtime.RequiredError(
                'apiContentUnitSearchRequest',
                'Required parameter "apiContentUnitSearchRequest" was null or undefined when calling searchPackageGroup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/package_groups/names`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApiContentUnitSearchRequestToJSON(requestParameters['apiContentUnitSearchRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ApiSearchPackageGroupResponseFromJSON));
    }

    /**
     * This enables users to search for package groups in a given list of repositories.
     * Search package groups
     */
    async searchPackageGroup(requestParameters: SearchPackageGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ApiSearchPackageGroupResponse>> {
        const response = await this.searchPackageGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This enables users to search for package groups in a given list of snapshots.
     * Search package groups within snapshots
     */
    async searchSnapshotPackageGroupsRaw(requestParameters: SearchSnapshotPackageGroupsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ApiSearchPackageGroupResponse>>> {
        if (requestParameters['apiSnapshotSearchRpmRequest'] == null) {
            throw new runtime.RequiredError(
                'apiSnapshotSearchRpmRequest',
                'Required parameter "apiSnapshotSearchRpmRequest" was null or undefined when calling searchSnapshotPackageGroups().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/snapshots/package_groups/names`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApiSnapshotSearchRpmRequestToJSON(requestParameters['apiSnapshotSearchRpmRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ApiSearchPackageGroupResponseFromJSON));
    }

    /**
     * This enables users to search for package groups in a given list of snapshots.
     * Search package groups within snapshots
     */
    async searchSnapshotPackageGroups(requestParameters: SearchSnapshotPackageGroupsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ApiSearchPackageGroupResponse>> {
        const response = await this.searchSnapshotPackageGroupsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
