// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: beacon_sync.sql

package store

import (
	"context"
	"time"
)

const getBeaconSync = `-- name: GetBeaconSync :one
SELECT last_processed_at
FROM lightwell_beacon_sync
WHERE id = true
`

func (q *Queries) GetBeaconSync(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, getBeaconSync)
	var last_processed_at time.Time
	err := row.Scan(&last_processed_at)
	return last_processed_at, err
}

const recordBeaconSync = `-- name: RecordBeaconSync :exec
INSERT INTO lightwell_beacon_sync (id, last_processed_at)
VALUES (true, $1)
ON CONFLICT (id) DO UPDATE SET
    last_processed_at = EXCLUDED.last_processed_at
`

func (q *Queries) RecordBeaconSync(ctx context.Context, lastProcessedAt time.Time) error {
	_, err := q.db.Exec(ctx, recordBeaconSync, lastProcessedAt)
	return err
}
