// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"time"

	"github.com/google/uuid"
)

type LightwellVulnerability struct {
	Uuid               uuid.UUID `json:"uuid"`
	VulnerabilityID    string    `json:"vulnerability_id"`
	Purl               *string   `json:"purl"`
	ComponentName      string    `json:"component_name"`
	ComponentVersion   string    `json:"component_version"`
	Title              *string   `json:"title"`
	Cwe                *string   `json:"cwe"`
	Description        *string   `json:"description"`
	Severity           string    `json:"severity"`
	Cvss               *float64  `json:"cvss"`
	CvssVector         *string   `json:"cvss_vector"`
	ExploitTested      bool      `json:"exploit_tested"`
	ReproducerIncluded bool      `json:"reproducer_included"`
	CustomerPriority   *string   `json:"customer_priority"`
	Stage              string    `json:"stage"`
	Language           *string   `json:"language"`
	Complexity         string    `json:"complexity"`
	SubmittedDate      time.Time `json:"submitted_date"`
	LastUpdated        time.Time `json:"last_updated"`
	Embargo            bool      `json:"embargo"`
	Duplicate          bool      `json:"duplicate"`
	LtwwlsuptTicketID  string    `json:"ltwwlsupt_ticket_id"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
}

type LightwellVulnerabilityCustomer struct {
	CustomerID        string    `json:"customer_id"`
	VulnerabilityUuid uuid.UUID `json:"vulnerability_uuid"`
	CreatedAt         time.Time `json:"created_at"`
}
