// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/google/uuid"
)

type LightwellAdvisory struct {
	Uuid                        uuid.UUID `json:"uuid"`
	CreatedAt                   time.Time `json:"created_at"`
	UpdatedAt                   time.Time `json:"updated_at"`
	RepoName                    string    `json:"repo_name"`
	AdvisoryID                  string    `json:"advisory_id"`
	Severity                    string    `json:"severity"`
	SeverityOrder               int16     `json:"severity_order"`
	Details                     string    `json:"details"`
	ReferenceUrls               []string  `json:"reference_urls"`
	PackageName                 string    `json:"package_name"`
	FixedVersion                string    `json:"fixed_version"`
	FixedVersions               []string  `json:"fixed_versions"`
	RepositoryConfigurationUuid uuid.UUID `json:"repository_configuration_uuid"`
	Checksum                    string    `json:"checksum"`
}

type LightwellVulnerability struct {
	Uuid               uuid.UUID `json:"uuid"`
	VulnerabilityID    string    `json:"vulnerability_id"`
	Purl               *string   `json:"purl"`
	ComponentName      string    `json:"component_name"`
	ComponentVersion   string    `json:"component_version"`
	Title              *string   `json:"title"`
	Cwe                *string   `json:"cwe"`
	Description        *string   `json:"description"`
	Severity           string    `json:"severity"`
	Cvss               *float64  `json:"cvss"`
	CvssVector         *string   `json:"cvss_vector"`
	ExploitTested      bool      `json:"exploit_tested"`
	ReproducerIncluded bool      `json:"reproducer_included"`
	CustomerPriority   *string   `json:"customer_priority"`
	Stage              string    `json:"stage"`
	Language           *string   `json:"language"`
	Complexity         string    `json:"complexity"`
	SubmittedDate      time.Time `json:"submitted_date"`
	LastUpdated        time.Time `json:"last_updated"`
	Embargo            bool      `json:"embargo"`
	Duplicate          bool      `json:"duplicate"`
	DuplicateOf        *string   `json:"duplicate_of"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
}

type LightwellVulnerabilityCustomer struct {
	CustomerID        string    `json:"customer_id"`
	VulnerabilityUuid uuid.UUID `json:"vulnerability_uuid"`
	CreatedAt         time.Time `json:"created_at"`
}

type RepositoryConfiguration struct {
	Uuid uuid.UUID `json:"uuid"`
}
