// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	CountAggregates(ctx context.Context, arg CountAggregatesParams) (CountAggregatesRow, error)
	CountByStage(ctx context.Context, arg CountByStageParams) ([]CountByStageRow, error)
	CreateCustomerStaml(ctx context.Context, arg CreateCustomerStamlParams) (LightwellCustomerStaml, error)
	CustomerStamlExists(ctx context.Context, arg CustomerStamlExistsParams) (bool, error)
	DeleteCustomerStaml(ctx context.Context, arg DeleteCustomerStamlParams) (int64, error)
	ListCustomerIdsByStaml(ctx context.Context, staml string) ([]string, error)
	ListLtwlsuptTicketIds(ctx context.Context, customerID string) ([]string, error)
	ListVulnerabilities(ctx context.Context, arg ListVulnerabilitiesParams) ([]ListVulnerabilitiesRow, error)
}

var _ Querier = (*Queries)(nil)
