#!/usr/bin/env bash
#
# Render the Lightwell access-tokens VHS demo (GIF + MP4).
#
# Prerequisites:
#   - brew install vhs  (pulls ttyd + ffmpeg on macOS)
#   - make run with Lightwell enabled and a seeded repo
#
# Usage:
#   REPO_UUID=<uuid> ./scripts/render_lightwell_tokens_demo.sh
#
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "${ROOT_DIR}"

CS_BASE="${CS_BASE:-http://localhost:8000}"
ORG_ID="${ORG_ID:-9999}"
USER_ID="${USER_ID:-1111}"
REPO_UUID="${REPO_UUID:-}"
STEP_PAUSE="${STEP_PAUSE:-2}"
DEMO_ENV="${ROOT_DIR}/docs/demos/.lightwell_demo_env"
TAPE="${ROOT_DIR}/docs/demos/lightwell_tokens.tape"

if [[ -z "${REPO_UUID}" ]]; then
  echo "ERROR: REPO_UUID is required." >&2
  echo "  List Lightwell repos:" >&2
  echo "    curl -s -H \"\$($(dirname "$0")/header_org_admin.sh 9999 1111)\" \\" >&2
  echo "      ${CS_BASE}/api/content-sources/v1.0/repositories/?origin=lightwell | jq '.data[] | {uuid,name}'" >&2
  exit 1
fi

if ! command -v vhs >/dev/null 2>&1; then
  echo "ERROR: vhs not found. Install with: brew install vhs" >&2
  exit 1
fi

# Quick health check so VHS does not record a long failure.
HDR="$("$(dirname "$0")/header_org_admin.sh" "${ORG_ID}" "${USER_ID}")"
code=$(curl -s -o /dev/null -w '%{http_code}' -H "${HDR}" \
  "${CS_BASE}/api/content-sources/v1.0/repositories/${REPO_UUID}/packages?limit=1" || true)
if [[ "${code}" != "200" ]]; then
  echo "ERROR: packages endpoint returned HTTP ${code} for REPO_UUID=${REPO_UUID}" >&2
  echo "  Is make run up at ${CS_BASE}? Is the repo seeded?" >&2
  exit 1
fi

mkdir -p "${ROOT_DIR}/docs/demos"

cat > "${DEMO_ENV}" <<EOF
# Generated by scripts/render_lightwell_tokens_demo.sh — do not commit.
cd "${ROOT_DIR}"
export CS_BASE="${CS_BASE}"
export ORG_ID="${ORG_ID}"
export USER_ID="${USER_ID}"
export REPO_UUID="${REPO_UUID}"
export STEP_PAUSE="${STEP_PAUSE}"
EOF

echo "Rendering ${TAPE} (REPO_UUID=${REPO_UUID})..."
vhs "${TAPE}"
echo "Wrote docs/demos/lightwell_tokens.gif and docs/demos/lightwell_tokens.mp4"
