apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/content-services/content-sources-backend?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "main"
    pipelinesascode.tekton.dev/pipeline: https://github.com/RedHatInsights/konflux-pipelines/raw/main/pipelines/docker-build-oci-ta.yaml
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: insights-content-sources
    appstudio.openshift.io/component: content-sources-backend
    pipelines.appstudio.openshift.io/type: build
  name: content-sources-backend-on-push
  namespace: insights-management-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/insights-management-tenant/insights-content-sources/content-sources-backend:{{revision}}
  - name: dockerfile
    value: build/Dockerfile
  - name: path-context
    value: .
  pipelineRef:
    name: docker-build-oci-ta
  taskRunTemplate:
    serviceAccountName: build-pipeline-content-sources-backend
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
