// Code generated by mockery. DO NOT EDIT.

package dao

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockDomainDao is an autogenerated mock type for the DomainDao type
type MockDomainDao struct {
	mock.Mock
}

// Fetch provides a mock function with given fields: ctx, orgId
func (_m *MockDomainDao) Fetch(ctx context.Context, orgId string) (string, error) {
	ret := _m.Called(ctx, orgId)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, orgId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, orgId)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orgId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchOrCreateDomain provides a mock function with given fields: ctx, orgId
func (_m *MockDomainDao) FetchOrCreateDomain(ctx context.Context, orgId string) (string, error) {
	ret := _m.Called(ctx, orgId)

	if len(ret) == 0 {
		panic("no return value specified for FetchOrCreateDomain")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, orgId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, orgId)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orgId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RenameDomain provides a mock function with given fields: ctx, orgId, newDomainName
func (_m *MockDomainDao) RenameDomain(ctx context.Context, orgId string, newDomainName string) error {
	ret := _m.Called(ctx, orgId, newDomainName)

	if len(ret) == 0 {
		panic("no return value specified for RenameDomain")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, orgId, newDomainName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockDomainDao creates a new instance of MockDomainDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDomainDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDomainDao {
	mock := &MockDomainDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
