// Code generated by mockery v2.32.0. DO NOT EDIT.

package dao

import (
	context "context"

	api "github.com/content-services/content-sources-backend/pkg/api"

	mock "github.com/stretchr/testify/mock"

	models "github.com/content-services/content-sources-backend/pkg/models"
)

// MockSnapshotDao is an autogenerated mock type for the SnapshotDao type
type MockSnapshotDao struct {
	mock.Mock
}

// Create provides a mock function with given fields: snap
func (_m *MockSnapshotDao) Create(snap *models.Snapshot) error {
	ret := _m.Called(snap)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Snapshot) error); ok {
		r0 = rf(snap)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: snapUUID
func (_m *MockSnapshotDao) Delete(snapUUID string) error {
	ret := _m.Called(snapUUID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(snapUUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FetchForRepoConfigUUID provides a mock function with given fields: repoConfigUUID
func (_m *MockSnapshotDao) FetchForRepoConfigUUID(repoConfigUUID string) ([]models.Snapshot, error) {
	ret := _m.Called(repoConfigUUID)

	var r0 []models.Snapshot
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]models.Snapshot, error)); ok {
		return rf(repoConfigUUID)
	}
	if rf, ok := ret.Get(0).(func(string) []models.Snapshot); ok {
		r0 = rf(repoConfigUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Snapshot)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(repoConfigUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchLatestSnapshot provides a mock function with given fields: repoConfigUUID
func (_m *MockSnapshotDao) FetchLatestSnapshot(repoConfigUUID string) (api.SnapshotResponse, error) {
	ret := _m.Called(repoConfigUUID)

	var r0 api.SnapshotResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (api.SnapshotResponse, error)); ok {
		return rf(repoConfigUUID)
	}
	if rf, ok := ret.Get(0).(func(string) api.SnapshotResponse); ok {
		r0 = rf(repoConfigUUID)
	} else {
		r0 = ret.Get(0).(api.SnapshotResponse)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(repoConfigUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRepositoryConfigurationFile provides a mock function with given fields: orgID, snapshotUUID, repoConfigUUID
func (_m *MockSnapshotDao) GetRepositoryConfigurationFile(orgID string, snapshotUUID string, repoConfigUUID string) (string, error) {
	ret := _m.Called(orgID, snapshotUUID, repoConfigUUID)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (string, error)); ok {
		return rf(orgID, snapshotUUID, repoConfigUUID)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) string); ok {
		r0 = rf(orgID, snapshotUUID, repoConfigUUID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(orgID, snapshotUUID, repoConfigUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InitializePulpClient provides a mock function with given fields: ctx, orgID
func (_m *MockSnapshotDao) InitializePulpClient(ctx context.Context, orgID string) error {
	ret := _m.Called(ctx, orgID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, orgID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with given fields: repoConfigUuid, paginationData, _a2
func (_m *MockSnapshotDao) List(repoConfigUuid string, paginationData api.PaginationData, _a2 api.FilterData) (api.SnapshotCollectionResponse, int64, error) {
	ret := _m.Called(repoConfigUuid, paginationData, _a2)

	var r0 api.SnapshotCollectionResponse
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(string, api.PaginationData, api.FilterData) (api.SnapshotCollectionResponse, int64, error)); ok {
		return rf(repoConfigUuid, paginationData, _a2)
	}
	if rf, ok := ret.Get(0).(func(string, api.PaginationData, api.FilterData) api.SnapshotCollectionResponse); ok {
		r0 = rf(repoConfigUuid, paginationData, _a2)
	} else {
		r0 = ret.Get(0).(api.SnapshotCollectionResponse)
	}

	if rf, ok := ret.Get(1).(func(string, api.PaginationData, api.FilterData) int64); ok {
		r1 = rf(repoConfigUuid, paginationData, _a2)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(string, api.PaginationData, api.FilterData) error); ok {
		r2 = rf(repoConfigUuid, paginationData, _a2)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewMockSnapshotDao creates a new instance of MockSnapshotDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSnapshotDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSnapshotDao {
	mock := &MockSnapshotDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
