@startuml
'https://plantuml.com/deployment-diagram
title Connection Diagram
database postgreql
queue Kafka as kafka
cloud {
  actor "Api Client" as user
  component "Yum/Dnf Client" as yumClient
}

cloud "Third Party Yum Repo" as yumRepo

component "Http Api" as api
component "Task Worker" as taskWorker
component "Pulp Server" as pulp
queue "Redis cache" as redis


user -down-> api : "Web Request"
api -right-> postgreql
api --> yumRepo: "Validates repomd"
api --> kafka: Notifications
api --> redis
taskWorker -left-> postgreql
taskWorker --> yumRepo: Downloads Primary XML
taskWorker -right-> pulp
yumClient -down-> pulp
pulp --> yumRepo: Syncs Repo

@enduml
