@startuml
hide circle
skinparam linetype ortho

entity "**domains**" {
  --
  *""org_id"": //character varying(255) //
  *""domain_name"": //character varying(255) //
}

entity "**environments**" {
  + ""uuid"": //uuid [PK]//
  --
  ""created_at"": //timestamp with time zone //
  ""updated_at"": //timestamp with time zone //
  *""id"": //text //
  *""name"": //text //
  ""description"": //text //
}

entity "**module_streams**" {
  + ""uuid"": //uuid [PK]//
  --
  ""created_at"": //timestamp with time zone //
  ""updated_at"": //timestamp with time zone //
  *""name"": //text //
  *""stream"": //text //
  *""version"": //text //
  *""context"": //text //
  *""arch"": //text //
  *""summary"": //text //
  *""description"": //text //
  *""package_names"": //text[] //
  *""packages"": //text[] //
  *""hash_value"": //text //
  *""profiles"": //jsonb //
}

entity "**package_groups**" {
  + ""uuid"": //uuid [PK]//
  --
  ""created_at"": //timestamp with time zone //
  ""updated_at"": //timestamp with time zone //
  *""id"": //text //
  *""name"": //text //
  ""description"": //text //
  ""package_list"": //text[] //
  ""hash_value"": //text //
}

entity "**repositories**" {
  + ""uuid"": //uuid [PK]//
  --
  ""created_at"": //timestamp with time zone //
  ""updated_at"": //timestamp with time zone //
  ""url"": //character varying(255) //
  *""public"": //boolean //
  ""last_introspection_time"": //timestamp with time zone //
  ""last_introspection_success_time"": //timestamp with time zone //
  ""last_introspection_update_time"": //timestamp with time zone //
  ""last_introspection_error"": //character varying(255) //
  ""last_introspection_status"": //character varying(255) //
  ""package_count"": //integer //
  *""repomd_checksum"": //character varying //
  *""failed_introspections_count"": //integer //
  *""origin"": //character varying //
  *""content_type"": //character varying //
}

entity "**repositories_environments**" {
  + ""repository_uuid"": //uuid [PK][FK]//
  + ""environment_uuid"": //uuid [PK][FK]//
  --
}

entity "**repositories_module_streams**" {
  + ""repository_uuid"": //uuid [PK][FK]//
  + ""module_stream_uuid"": //uuid [PK][FK]//
  --
}

entity "**repositories_package_groups**" {
  + ""repository_uuid"": //uuid [PK][FK]//
  + ""package_group_uuid"": //uuid [PK][FK]//
  --
}

entity "**repositories_rpms**" {
  + ""repository_uuid"": //uuid [PK][FK]//
  + ""rpm_uuid"": //uuid [PK][FK]//
  --
}

entity "**repository_configurations**" {
  + ""uuid"": //uuid [PK]//
  --
  *""created_at"": //timestamp with time zone //
  *""updated_at"": //timestamp with time zone //
  *""name"": //character varying(255) //
  ""versions"": //character varying(255)[] //
  *""arch"": //character varying(255) //
  ""account_id"": //character varying(255) //
  *""org_id"": //character varying(255) //
  *""repository_uuid"": //uuid [FK]//
  ""gpg_key"": //text //
  *""metadata_verification"": //boolean //
  ""snapshot"": //boolean //
  ""deleted_at"": //timestamp with time zone //
  ""last_snapshot_uuid"": //uuid [FK]//
  ""last_snapshot_task_uuid"": //uuid [FK]//
  *""module_hotfixes"": //boolean //
  *""label"": //character varying(255) //
  ""feature_name"": //character varying(255) //
  *""failed_snapshot_count"": //integer //
}

entity "**rpms**" {
  + ""uuid"": //uuid [PK]//
  --
  ""created_at"": //timestamp with time zone //
  ""updated_at"": //timestamp with time zone //
  *""name"": //text //
  *""arch"": //text //
  *""version"": //text //
  ""release"": //text //
  *""epoch"": //integer //
  *""summary"": //text //
  *""checksum"": //text //
}

entity "**schema_migrations**" {
  + ""version"": //bigint [PK]//
  --
  *""dirty"": //boolean //
}

entity "**snapshots**" {
  + ""uuid"": //uuid [PK]//
  --
  ""created_at"": //timestamp with time zone //
  ""updated_at"": //timestamp with time zone //
  *""content_counts"": //jsonb //
  *""version_href"": //character varying //
  *""publication_href"": //character varying //
  *""distribution_path"": //character varying //
  *""distribution_href"": //character varying //
  *""repository_path"": //character varying //
  *""repository_configuration_uuid"": //uuid [FK]//
  *""added_counts"": //jsonb //
  *""removed_counts"": //jsonb //
  ""deleted_at"": //timestamp with time zone //
}

entity "**task_dependencies**" {
  --
  ""task_id"": //uuid [FK]//
  ""dependency_id"": //uuid [FK]//
}

entity "**task_heartbeats**" {
  + ""token"": //uuid [PK]//
  --
  ""id"": //uuid [FK]//
  *""heartbeat"": //timestamp with time zone //
}

entity "**tasks**" {
  + ""id"": //uuid [PK]//
  --
  ""org_id"": //character varying //
  ""token"": //uuid //
  *""type"": //character varying //
  ""payload"": //jsonb //
  ""status"": //character varying //
  ""error"": //character varying(4000) //
  ""queued_at"": //timestamp with time zone //
  ""started_at"": //timestamp with time zone //
  ""finished_at"": //timestamp with time zone //
  ""request_id"": //character varying //
  ""account_id"": //character varying //
  ""retries"": //integer //
  ""next_retry_time"": //timestamp with time zone //
  ""priority"": //integer //
  ""object_uuid"": //uuid //
  ""object_type"": //character varying(255) //
  ""cancel_attempted"": //boolean //
}

entity "**templates**" {
  + ""uuid"": //uuid [PK]//
  --
  *""org_id"": //character varying(255) //
  ""created_at"": //timestamp with time zone //
  ""updated_at"": //timestamp with time zone //
  *""name"": //character varying(255) //
  ""description"": //character varying(255) //
  ""date"": //timestamp with time zone //
  ""version"": //character varying(255) //
  ""arch"": //character varying(255) //
  ""deleted_at"": //timestamp with time zone //
  ""created_by"": //character varying //
  ""last_updated_by"": //character varying //
  *""use_latest"": //boolean //
  ""last_update_snapshot_error"": //character varying(255) //
  ""last_update_task_uuid"": //uuid //
  *""rhsm_environment_created"": //boolean //
}

entity "**templates_repository_configurations**" {
  + ""template_uuid"": //uuid [PK]//
  + ""repository_configuration_uuid"": //uuid [PK]//
  --
  *""template_uuid"": //uuid [FK]//
  *""repository_configuration_uuid"": //uuid [FK]//
  ""distribution_href"": //character varying(255) //
  ""deleted_at"": //timestamp with time zone //
  *""snapshot_uuid"": //uuid [FK]//
}

entity "**uploads**" {
  + ""upload_uuid"": //text [PK]//
  --
  ""created_at"": //timestamp with time zone //
  *""org_id"": //character varying(255) //
  *""chunk_size"": //integer //
  *""sha256"": //text //
  *""chunk_list"": //text[] //
  *""size"": //integer //
}

"**repositories_environments**"   }--  "**environments**"

"**repositories_environments**"   }--  "**repositories**"

"**repositories_module_streams**"   }--  "**module_streams**"

"**repositories_module_streams**"   }--  "**module_streams**"

"**repositories_module_streams**"   }--  "**repositories**"

"**repositories_package_groups**"   }--  "**package_groups**"

"**repositories_package_groups**"   }--  "**repositories**"

"**repositories_rpms**"   }--  "**repositories**"

"**repositories_rpms**"   }--  "**rpms**"

"**repository_configurations**"   }--  "**snapshots**"

"**repository_configurations**"   }--  "**tasks**"

"**repository_configurations**"   }--  "**repositories**"

"**snapshots**"   }--  "**repository_configurations**"

"**task_dependencies**"   }--  "**tasks**"

"**task_dependencies**"   }--  "**tasks**"

"**task_heartbeats**"   }--  "**tasks**"

"**templates_repository_configurations**"   }--  "**repository_configurations**"

"**templates_repository_configurations**"   }--  "**repository_configurations**"

"**templates_repository_configurations**"   }--  "**snapshots**"

"**templates_repository_configurations**"   }--  "**templates**"

"**templates_repository_configurations**"   }--  "**templates**"
@enduml
