// Package api GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "https://www.apache.org/licenses/LICENSE-2.0"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/features/": {
            "get": {
                "description": "Get features available for the user within their Organization",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "features"
                ],
                "summary": "List Features within the application, whether they are enabled, and whether the requesting user can use them",
                "operationId": "listFeatures",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.FeatureSet"
                        }
                    }
                }
            }
        },
        "/popular_repositories/": {
            "get": {
                "description": "Get popular repositories",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "popular_repositories"
                ],
                "summary": "List Popular Repositories",
                "operationId": "listPopularRepositories",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.PopularRepositoriesCollectionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/public_repositories/": {
            "get": {
                "description": "Get public repositories.\nA public repository is a defined repository that is available to all accounts for the purposes of searching for rpm names by URL.\nIt does not show up via the normal repositories API.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "public_repositories"
                ],
                "summary": "List Public Repositories",
                "operationId": "listPublicRepositories",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Offset into the list of results to return in the response",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit the number of items returned",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.PublicRepositoryCollectionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/repositories/": {
            "get": {
                "description": "list repositories",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repositories"
                ],
                "summary": "List Repositories",
                "operationId": "listRepositories",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Offset into the list of results to return in the response",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit the number of items returned",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Comma separated list of architecture to optionally filter-on (e.g. 'x86_64,s390x' would return Repositories with x86_64 or s390x only)",
                        "name": "version",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Comma separated list of versions to optionally filter-on  (e.g. '7,8' would return Repositories with versions 7 or 8 only)",
                        "name": "arch",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by compatible arch (e.g. 'x86_64' would return Repositories with the 'x86_64' arch and Repositories where arch is not set)",
                        "name": "available_for_version",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by compatible version (e.g. 7 would return Repositories with the version 7 or where version is not set)",
                        "name": "available_for_arch",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search term for name and url.",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter repositories by name using an exact match",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter repositories by name using an exact match",
                        "name": "url",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sets the sort order of the results",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Comma separated list of statuses to optionally filter on",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.RepositoryCollectionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "create a repository",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repositories"
                ],
                "summary": "Create Repository",
                "operationId": "createRepository",
                "parameters": [
                    {
                        "description": "request body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.RepositoryRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api.RepositoryResponse"
                        },
                        "headers": {
                            "Location": {
                                "type": "string",
                                "description": "resource URL"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "415": {
                        "description": "Unsupported Media Type",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/repositories/bulk_create/": {
            "post": {
                "description": "bulk create repositories",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repositories"
                ],
                "summary": "Bulk create repositories",
                "operationId": "bulkCreateRepositories",
                "parameters": [
                    {
                        "description": "request body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.RepositoryRequest"
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.RepositoryResponse"
                            }
                        },
                        "headers": {
                            "Location": {
                                "type": "string",
                                "description": "resource URL"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "415": {
                        "description": "Unsupported Media Type",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/repositories/{uuid}": {
            "get": {
                "description": "Get information about a Repository",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repositories"
                ],
                "summary": "Get Repository",
                "operationId": "getRepository",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Identifier of the Repository",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.RepositoryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Fully update a repository",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repositories"
                ],
                "summary": "Update Repository",
                "operationId": "fullUpdateRepository",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Identifier of the Repository",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "request body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.RepositoryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.RepositoryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "415": {
                        "description": "Unsupported Media Type",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "repositories"
                ],
                "summary": "Delete a repository",
                "operationId": "deleteRepository",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Identifier of the Repository",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Repository was successfully deleted"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Partially Update a repository",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repositories"
                ],
                "summary": "Partial Update Repository",
                "operationId": "partialUpdateRepository",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Identifier of the Repository",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "request body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.RepositoryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.RepositoryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "415": {
                        "description": "Unsupported Media Type",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/repositories/{uuid}/introspect/": {
            "post": {
                "tags": [
                    "repositories"
                ],
                "summary": "introspect a repository",
                "operationId": "introspect",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Identifier of the Repository",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "request body",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/api.RepositoryIntrospectRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Introspection was successfully queued"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/repositories/{uuid}/rpms": {
            "get": {
                "description": "list repositories RPMs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repositories",
                    "rpms"
                ],
                "summary": "List Repositories RPMs",
                "operationId": "listRepositoriesRpms",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Identifier of the Repository",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Limit the number of items returned",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset into the list of results to return in the response",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search term for name.",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sets the sort order of the results.",
                        "name": "sort_by",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.RepositoryRpmCollectionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/repositories/{uuid}/snapshots/": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repositories"
                ],
                "summary": "List snapshots of a repository",
                "operationId": "listSnapshots",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Identifier of the Repository",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SnapshotCollectionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/repository_parameters/": {
            "get": {
                "description": "get repository parameters (Versions and Architectures)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repositories"
                ],
                "summary": "List Repository Parameters",
                "operationId": "listRepositoryParameters",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.RepositoryParameterResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/repository_parameters/external_gpg_key": {
            "post": {
                "description": "Fetch gpgkey from URL",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "gpgKey"
                ],
                "summary": "Fetch gpgkey from URL",
                "operationId": "fetchGpgKey",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.FetchGPGKeyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "415": {
                        "description": "Unsupported Media Type",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/repository_parameters/validate/": {
            "post": {
                "description": "Validate parameters prior to creating a repository, including checking if remote yum metadata is present",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repositories"
                ],
                "summary": "Validate parameters prior to creating a repository",
                "operationId": "validateRepositoryParameters",
                "parameters": [
                    {
                        "description": "request body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.RepositoryValidationRequest"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.RepositoryValidationResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "415": {
                        "description": "Unsupported Media Type",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/rpms/names": {
            "post": {
                "description": "Search RPMs for a given list of repositories as URLs or UUIDs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repositories",
                    "rpms"
                ],
                "summary": "Search RPMs",
                "operationId": "searchRpm",
                "parameters": [
                    {
                        "description": "request body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.SearchRpmRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.SearchRpmResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "415": {
                        "description": "Unsupported Media Type",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tasks/": {
            "get": {
                "description": "list tasks",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "List Tasks",
                "operationId": "listTasks",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Offset into the list of results to return in the response",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit the number of items returned",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter tasks by status using an exact match",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.TaskInfoCollectionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tasks/{uuid}": {
            "get": {
                "description": "Get information about a Task",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Get Task",
                "operationId": "getTask",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Identifier of the Task",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.TaskInfoResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errors.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.Feature": {
            "type": "object",
            "properties": {
                "accessible": {
                    "description": "Whether the current user can access the feature",
                    "type": "boolean"
                },
                "enabled": {
                    "description": "Whether the feature is enabled on the running server",
                    "type": "boolean"
                }
            }
        },
        "api.FeatureSet": {
            "type": "object",
            "additionalProperties": {
                "$ref": "#/definitions/api.Feature"
            }
        },
        "api.FetchGPGKeyResponse": {
            "type": "object",
            "properties": {
                "gpg_key": {
                    "description": "The downloaded GPG Keys from the provided url.",
                    "type": "string"
                }
            }
        },
        "api.GenericAttributeValidationResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "description": "Error message if the attribute is not valid",
                    "type": "string"
                },
                "skipped": {
                    "description": "Skipped if the attribute is not passed in for validation",
                    "type": "boolean"
                },
                "valid": {
                    "description": "Valid if not skipped and the provided attribute is valid",
                    "type": "boolean"
                }
            }
        },
        "api.Links": {
            "type": "object",
            "properties": {
                "first": {
                    "description": "Path to first page of results",
                    "type": "string"
                },
                "last": {
                    "description": "Path to last page of results",
                    "type": "string"
                },
                "next": {
                    "description": "Path to next page of results",
                    "type": "string"
                },
                "prev": {
                    "description": "Path to previous page of results",
                    "type": "string"
                }
            }
        },
        "api.PopularRepositoriesCollectionResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.PopularRepositoryResponse"
                    }
                },
                "links": {
                    "description": "Links to other pages of results",
                    "$ref": "#/definitions/api.Links"
                },
                "meta": {
                    "description": "Metadata about the request",
                    "$ref": "#/definitions/api.ResponseMetadata"
                }
            }
        },
        "api.PopularRepositoryResponse": {
            "type": "object",
            "properties": {
                "distribution_arch": {
                    "description": "Architecture to restrict client usage to",
                    "type": "string",
                    "example": "x86_64"
                },
                "distribution_versions": {
                    "description": "Versions to restrict client usage to",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "7",
                        "8"
                    ]
                },
                "existing_name": {
                    "description": "Existing reference name for repository",
                    "type": "string"
                },
                "gpg_key": {
                    "description": "GPG key for repository",
                    "type": "string"
                },
                "metadata_verification": {
                    "description": "Verify packages",
                    "type": "boolean"
                },
                "suggested_name": {
                    "description": "Suggested name of the popular repository",
                    "type": "string"
                },
                "url": {
                    "description": "URL of the remote yum repository",
                    "type": "string"
                },
                "uuid": {
                    "description": "UUID of the repository if it exists for the user",
                    "type": "string"
                }
            }
        },
        "api.PublicRepositoryCollectionResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.PublicRepositoryResponse"
                    }
                },
                "links": {
                    "description": "Links to other pages of results",
                    "$ref": "#/definitions/api.Links"
                },
                "meta": {
                    "description": "Metadata about the request",
                    "$ref": "#/definitions/api.ResponseMetadata"
                }
            }
        },
        "api.PublicRepositoryResponse": {
            "type": "object",
            "properties": {
                "last_introspection_error": {
                    "description": "Error of last attempted introspection",
                    "type": "string"
                },
                "last_introspection_time": {
                    "description": "Timestamp of last attempted introspection",
                    "type": "string"
                },
                "last_success_introspection_time": {
                    "description": "Timestamp of last successful introspection",
                    "type": "string"
                },
                "last_update_introspection_time": {
                    "description": "Timestamp of last introspection that had updates",
                    "type": "string"
                },
                "package_count": {
                    "description": "Number of packages last read in the repository",
                    "type": "integer"
                },
                "status": {
                    "description": "Introspection status of the repository",
                    "type": "string"
                },
                "url": {
                    "description": "URL of the remote yum repository",
                    "type": "string"
                },
                "uuid": {
                    "description": "UUID of the repository if it exists for the user",
                    "type": "string"
                }
            }
        },
        "api.RepositoryCollectionResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "Requested Data",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.RepositoryResponse"
                    }
                },
                "links": {
                    "description": "Links to other pages of results",
                    "$ref": "#/definitions/api.Links"
                },
                "meta": {
                    "description": "Metadata about the request",
                    "$ref": "#/definitions/api.ResponseMetadata"
                }
            }
        },
        "api.RepositoryIntrospectRequest": {
            "type": "object",
            "properties": {
                "reset_count": {
                    "description": "Reset the failed introspections count",
                    "type": "boolean"
                }
            }
        },
        "api.RepositoryParameterResponse": {
            "type": "object",
            "properties": {
                "distribution_arches": {
                    "description": "Architectures available for repository creation",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/config.DistributionArch"
                    }
                },
                "distribution_versions": {
                    "description": "Versions available for repository creation",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/config.DistributionVersion"
                    }
                }
            }
        },
        "api.RepositoryRequest": {
            "type": "object",
            "properties": {
                "distribution_arch": {
                    "description": "Architecture to restrict client usage to",
                    "type": "string",
                    "example": "x86_64"
                },
                "distribution_versions": {
                    "description": "Versions to restrict client usage to",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "7",
                        "8"
                    ]
                },
                "gpg_key": {
                    "description": "GPG key for repository",
                    "type": "string"
                },
                "metadata_verification": {
                    "description": "Verify packages",
                    "type": "boolean"
                },
                "name": {
                    "description": "Name of the remote yum repository",
                    "type": "string"
                },
                "snapshot": {
                    "description": "Enable snapshotting and hosting of this repository",
                    "type": "boolean"
                },
                "url": {
                    "description": "URL of the remote yum repository",
                    "type": "string"
                }
            }
        },
        "api.RepositoryResponse": {
            "type": "object",
            "properties": {
                "account_id": {
                    "description": "Account ID of the owner",
                    "type": "string",
                    "readOnly": true
                },
                "distribution_arch": {
                    "description": "Architecture to restrict client usage to",
                    "type": "string",
                    "example": "x86_64"
                },
                "distribution_versions": {
                    "description": "Versions to restrict client usage to",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "7",
                        "8"
                    ]
                },
                "failed_introspections_count": {
                    "description": "Number of consecutive failed introspections",
                    "type": "integer"
                },
                "gpg_key": {
                    "description": "GPG key for repository",
                    "type": "string"
                },
                "last_introspection_error": {
                    "description": "Error of last attempted introspection",
                    "type": "string"
                },
                "last_introspection_time": {
                    "description": "Timestamp of last attempted introspection",
                    "type": "string"
                },
                "last_success_introspection_time": {
                    "description": "Timestamp of last successful introspection",
                    "type": "string"
                },
                "last_update_introspection_time": {
                    "description": "Timestamp of last introspection that had updates",
                    "type": "string"
                },
                "metadata_verification": {
                    "description": "Verify packages",
                    "type": "boolean"
                },
                "name": {
                    "description": "Name of the remote yum repository",
                    "type": "string"
                },
                "org_id": {
                    "description": "Organization ID of the owner",
                    "type": "string",
                    "readOnly": true
                },
                "package_count": {
                    "description": "Number of packages last read in the repository",
                    "type": "integer"
                },
                "snapshot": {
                    "description": "Enable snapshotting and hosting of this repository",
                    "type": "boolean"
                },
                "status": {
                    "description": "Status of repository introspection (Valid, Invalid, Unavailable, Pending)",
                    "type": "string"
                },
                "url": {
                    "description": "URL of the remote yum repository",
                    "type": "string"
                },
                "uuid": {
                    "description": "UUID of the object",
                    "type": "string",
                    "readOnly": true
                }
            }
        },
        "api.RepositoryRpm": {
            "type": "object",
            "properties": {
                "arch": {
                    "description": "The Architecture of the rpm",
                    "type": "string"
                },
                "checksum": {
                    "description": "The checksum of the rpm",
                    "type": "string"
                },
                "epoch": {
                    "description": "The epoch of the rpm",
                    "type": "integer"
                },
                "name": {
                    "description": "The rpm package name",
                    "type": "string"
                },
                "release": {
                    "description": "The release of the rpm",
                    "type": "string"
                },
                "summary": {
                    "description": "The summary of the rpm",
                    "type": "string"
                },
                "uuid": {
                    "description": "Identifier of the rpm",
                    "type": "string"
                },
                "version": {
                    "description": "The version of the  rpm",
                    "type": "string"
                }
            }
        },
        "api.RepositoryRpmCollectionResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "List of rpms",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.RepositoryRpm"
                    }
                },
                "links": {
                    "description": "Links to other pages of results",
                    "$ref": "#/definitions/api.Links"
                },
                "meta": {
                    "description": "Metadata about the request",
                    "$ref": "#/definitions/api.ResponseMetadata"
                }
            }
        },
        "api.RepositoryValidationRequest": {
            "type": "object",
            "properties": {
                "gpg_key": {
                    "description": "GPGKey of the remote yum repository",
                    "type": "string"
                },
                "metadata_verification": {
                    "description": "If set, attempt to validate the yum metadata with the specified GPG Key",
                    "type": "boolean"
                },
                "name": {
                    "description": "Name of the remote yum repository",
                    "type": "string"
                },
                "url": {
                    "description": "URL of the remote yum repository",
                    "type": "string"
                },
                "uuid": {
                    "description": "If set, this is an \"Update\" validation",
                    "type": "string"
                }
            }
        },
        "api.RepositoryValidationResponse": {
            "type": "object",
            "properties": {
                "gpg_key": {
                    "description": "Validation response for the GPG Key",
                    "$ref": "#/definitions/api.GenericAttributeValidationResponse"
                },
                "name": {
                    "description": "Validation response for repository name",
                    "$ref": "#/definitions/api.GenericAttributeValidationResponse"
                },
                "url": {
                    "description": "Validation response for repository url",
                    "$ref": "#/definitions/api.UrlValidationResponse"
                }
            }
        },
        "api.ResponseMetadata": {
            "type": "object",
            "properties": {
                "count": {
                    "description": "Total count of results",
                    "type": "integer"
                },
                "limit": {
                    "description": "Limit of results used for the request",
                    "type": "integer"
                },
                "offset": {
                    "description": "Offset into results used for the request",
                    "type": "integer"
                }
            }
        },
        "api.SearchRpmRequest": {
            "type": "object",
            "properties": {
                "limit": {
                    "description": "Maximum number of records to return for the search",
                    "type": "integer"
                },
                "search": {
                    "description": "Search string to search rpm names",
                    "type": "string"
                },
                "urls": {
                    "description": "URLs of repositories to search",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "uuids": {
                    "description": "List of RepositoryConfig UUIDs to search",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "api.SearchRpmResponse": {
            "type": "object",
            "properties": {
                "package_name": {
                    "description": "Package name found",
                    "type": "string"
                },
                "summary": {
                    "description": "Summary of the package found",
                    "type": "string"
                }
            }
        },
        "api.SnapshotCollectionResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "Requested Data",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.SnapshotResponse"
                    }
                },
                "links": {
                    "description": "Links to other pages of results",
                    "$ref": "#/definitions/api.Links"
                },
                "meta": {
                    "description": "Metadata about the request",
                    "$ref": "#/definitions/api.ResponseMetadata"
                }
            }
        },
        "api.SnapshotResponse": {
            "type": "object",
            "properties": {
                "content_counts": {
                    "description": "Count of each content type",
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "created_at": {
                    "description": "Datetime the snapshot was created",
                    "type": "string"
                },
                "distribution_path": {
                    "description": "Path to pulp distribution",
                    "type": "string"
                }
            }
        },
        "api.TaskInfoCollectionResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "Requested Data",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.TaskInfoResponse"
                    }
                },
                "links": {
                    "description": "Links to other pages of results",
                    "$ref": "#/definitions/api.Links"
                },
                "meta": {
                    "description": "Metadata about the request",
                    "$ref": "#/definitions/api.ResponseMetadata"
                }
            }
        },
        "api.TaskInfoResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "Timestamp of task creation",
                    "type": "string"
                },
                "ended_at": {
                    "description": "Timestamp task ended running at",
                    "type": "string"
                },
                "error": {
                    "description": "Error thrown while running task",
                    "type": "string"
                },
                "org_id": {
                    "description": "Organization ID of the owner",
                    "type": "string"
                },
                "status": {
                    "description": "Status of task (running, failed, completed, canceled, pending)",
                    "type": "string"
                },
                "uuid": {
                    "description": "UUID of the object",
                    "type": "string"
                }
            }
        },
        "api.UrlValidationResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "description": "Error message if the attribute is not valid",
                    "type": "string"
                },
                "http_code": {
                    "description": "If the metadata cannot be fetched successfully, the http code that is returned if the http request was completed",
                    "type": "integer"
                },
                "metadata_present": {
                    "description": "True if the metadata can be fetched successfully",
                    "type": "boolean"
                },
                "metadata_signature_present": {
                    "description": "True if a repomd.xml.sig file was found in the repository",
                    "type": "boolean"
                },
                "skipped": {
                    "description": "Skipped if the URL is not passed in for validation",
                    "type": "boolean"
                },
                "valid": {
                    "description": "Valid if not skipped and the provided attribute is valid",
                    "type": "boolean"
                }
            }
        },
        "config.DistributionArch": {
            "type": "object",
            "properties": {
                "label": {
                    "description": "Static label of the architecture",
                    "type": "string"
                },
                "name": {
                    "description": "Human-readable form of the architecture",
                    "type": "string"
                }
            }
        },
        "config.DistributionVersion": {
            "type": "object",
            "properties": {
                "label": {
                    "description": "Static label of the version",
                    "type": "string"
                },
                "name": {
                    "description": "Human-readable form of the version",
                    "type": "string"
                }
            }
        },
        "errors.ErrorResponse": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/errors.HandlerError"
                    }
                }
            }
        },
        "errors.HandlerError": {
            "type": "object",
            "properties": {
                "detail": {
                    "description": "An explanation specific to the problem",
                    "type": "string"
                },
                "status": {
                    "description": "HTTP status code applicable to the error",
                    "type": "integer"
                },
                "title": {
                    "description": "A summary of the problem",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "RhIdentity": {
            "type": "apiKey",
            "name": "x-rh-identity",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "v1.0.0",
	Host:             "api.example.com",
	BasePath:         "/api/content-sources/v1.0/",
	Schemes:          []string{},
	Title:            "ContentSourcesBackend",
	Description:      "API of the Content Sources application on [console.redhat.com](https://console.redhat.com)\n",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
