name: Run playwright API tests
on: [push]

concurrency:
  group: integration-group # ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  Playwright-integration-test:
    runs-on:
      - codebuild-ContentSourcesCICDRunner-${{ github.run_id }}-${{ github.run_attempt }}
      - instance-size:small
      - buildspec-override:true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo "USER1USERNAME=${{ secrets.USER1USERNAME }}" >> .env
          echo "USER1PASSWORD=${{ secrets.USER1PASSWORD }}" >> .env
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env
          echo "PROXY=${{ secrets.PROXY }}" >> .env
          echo "TOKEN=apple" >> .env
          echo "CI=true" >> .env

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: yarn install

      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps

      - name: Run Playwright tests
        run: yarn playwright test

      - name: Publish Test Report
        uses: ctrf-io/github-test-reporter@v1
        with:
          report-path: "./playwright-ctrf/playwright-ctrf.json"
        #   pull-request-report: true
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: always()

        # run: npx github-actions-ctrf playwright-ctrf/playwright-ctrf.json

      - name: Store report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 10
