name: Fail on missing QE Approval
on:
  pull_request:
    types: [labeled, unlabled, opened, reopened, edited, synchronize]


jobs:
  check-qe-ack:
    name: Check QE Ack
    runs-on: ubuntu-latest
    if: ${{ !(contains(github.event.pull_request.labels.*.name, 'no-qe-needed') || contains(github.event.pull_request.labels.*.name, 'qe-approved')) }}
    steps:
      - shell: bash
        run: |
          echo "Approval by 'Quality Engineering' team required"
          exit -1
